"""Patient-facing message rewriting layer.

Clinical rule outputs (seed rules + clinician-authored rules + legacy
defaults) are written in clinical language. At the service boundary every
known recommendation string is rewritten into short, patient-friendly
English, so the frontend only needs to translate a small, stable set of
messages (see i18n exactTextMap). Unknown strings pass through unchanged
(whitespace-normalised so lookup/display stay stable).

To change wording: edit the values here, then mirror the change in the
frontend exactTextMap translations.
"""

LAB_NORMAL_BUT_SYMPTOMS_NOTE = "Your blood tests look normal today, but your symptoms are still classic diabetes signs — symptoms can appear before blood sugar rises. Keep watching them and re-test in 1–3 months."

COMPLETENESS_NOTE = "No blood test yet — that is OK for a screening. Your answers already give a useful signal; a simple fasting glucose or HbA1c test anytime will sharpen it."

URGENT_SAFETY_NOTE = "Seek urgent in-person medical care now. If symptoms are severe or getting worse, go straight to emergency care."

# whitespace-normalised original clinical text -> patient-friendly text
RECOMMENDATION_REWRITES: dict[str, str] = {
    "Take 15–20 g of fast-acting glucose (e.g., glucose tablets, juice). Recheck blood glucose in 15 minutes and repeat if still below 70 mg/dL.": "Low blood sugar right now. Take 15–20 g of fast sugar (glucose tablets or juice), then recheck in 15 minutes — repeat if still under 70.",
    "Clinically significant hypoglycemia. Administer fast-acting glucose immediately. If the patient is unable to swallow safely, administer glucagon and seek emergency medical care.": "Very low blood sugar. Take fast-acting sugar immediately. If swallowing is not safe, that is an emergency — call for medical help.",
    "Critical blood glucose level. Seek emergency medical care immediately. Monitor for signs of dehydration, confusion, or loss of consciousness.": "Dangerously high blood sugar. Seek emergency medical care now — watch for confusion, severe dehydration or fainting.",
    "Severely elevated HbA1c. Consider early insulin therapy and urgent endocrine referral. Evaluate for DKA risk factors.": "Your average blood sugar (HbA1c) is severely elevated. See a doctor urgently — treatment and a safety plan should start now.",
    "High risk of diabetes progression. Enroll in a structured lifestyle intervention program (target: ≥7% weight loss and ≥150 min/week moderate physical activity). Consider metformin for chemoprevention (especially if BMI ≥35 or age <60).": "High risk of progressing to type 2 diabetes. Losing about 7% of body weight, 150 minutes of activity a week, and a prevention talk with your doctor dramatically cut the risk.",
    "Possible diabetic ketoacidosis detected. Go to emergency care immediately. Do NOT delay. Blood ketone measurement, arterial blood gas, and IV fluids are likely needed.": "Signs of diabetic ketoacidosis (DKA) — a medical emergency. Go to emergency care now; do not wait for test results.",
    "Treat hypoglycemia with the 15/15 rule: take 15 g of fast-acting carbohydrate, wait 15 minutes, recheck glucose. Review diabetes medications with your doctor. If receiving insulin or sulfonylurea, dose adjustment may be needed.": "You had a low blood sugar episode. Use the 15/15 rule: 15 g of fast sugar, wait 15 minutes, recheck. Ask your doctor if any medication doses need adjusting.",
    "Prediabetes detected. Recommendations: (1) Aim for ≥7% body weight loss through dietary changes. (2) Engage in ≥150 minutes per week of moderate-intensity physical activity. (3) Repeat HbA1c and fasting glucose in 3–6 months. (4) Consider referral to a Diabetes Prevention Program (DPP).": "Prediabetes — a warning stage you can reverse. Lose about 7% of body weight, move 150 minutes a week, cut sugary drinks, and re-test in 3–6 months.",
    "Diabetes diagnostic criteria met. Schedule clinical evaluation including: (1) Confirmatory lab test if single abnormal result. (2) HbA1c target goal setting. (3) Retinal and foot examination. (4) Lipid panel and blood pressure assessment. (5) Diabetes self-management education and support (DSMES).": "Your results meet the diabetes criteria. Book a clinic visit within 1–2 weeks to confirm, set targets and start treatment.",
    "Assessment lacks laboratory data. A definitive diabetes diagnosis requires at least one of: (1) Fasting plasma glucose (≥8h fast). (2) HbA1c (NGSP-certified lab). (3) 75-g oral glucose tolerance test (2-hour value). Complete these tests to improve assessment reliability.": "No blood test yet — that is fine for a first screening. A simple fasting glucose or HbA1c test at any lab will make the result far more certain.",
    "Type 2 diabetes risk factors identified. ADA recommends: (1) Routine diabetes screening every 3 years. (2) If prediabetes, repeat testing every 1–2 years. (3) Maintain healthy weight (BMI <25). (4) Exercise ≥150 min/week. (5) Follow a balanced diet rich in whole grains, vegetables, and lean proteins.": "You carry type 2 risk factors. Keep a healthy weight, move 150 minutes a week, eat more whole foods, and screen every 1–3 years.",
    "Obesity identified (BMI ≥30). Weight management recommendations: (1) Target initial weight loss of 5–10% of body weight. (2) Caloric deficit through reduced portions and healthier food choices. (3) At least 150 minutes per week of moderate-intensity exercise. (4) Consider referral to dietitian or weight management program. (5) Screen for obstructive sleep apnea and metabolic syndrome.": "Weight is the biggest lever you control — a 5–10% loss lowers sugar, blood pressure and cholesterol together. A dietitian can help you build the plan.",
    "Diabetes confirmed by dual criteria. Comprehensive management plan: (1) Set individualized HbA1c target (generally <7% for most adults). (2) Initiate metformin as first-line therapy unless contraindicated. (3) Retinal screening within 5 years of diagnosis for T2D (at diagnosis for T1D). (4) Annual foot exam. (5) Lipid panel and statin therapy if indicated. (6) Blood pressure target <130/80 mmHg. (7) Diabetes self-management education. (8) Psychological well-being assessment.": "Diabetes is confirmed by two matching tests. Book your doctor within 1–2 weeks: sugar targets, metformin first (usually), plus eye and foot checks.",
    "Neuropathy Warning: Patient reports tingling in extremities. Recommend comprehensive foot exam, checking for peripheral pulse, and tuning fork/monofilament sensory assessment.": "Tingling in hands or feet can mean nerves are irritated by years of high sugar. Tell your doctor, and check your feet daily for numbness or sores.",
    "Metabolic Syndrome identified. Recommend intensive lifestyle intervention, lipid panel monitoring, cardiovascular risk stratification, and aggressive blood pressure control.": "Your blood pressure, weight and cholesterol pattern raise heart and diabetes risk. Move more, eat plainer, and treat blood pressure and cholesterol with your doctor.",
    "Patient has a history of Gestational Diabetes. ADA mandates lifelong screening for Type 2 Diabetes at least every 3 years, regardless of other risk factors.": "Past gestational diabetes raises type 2 risk for life. A quick glucose or HbA1c check every 1–3 years keeps you ahead of it.",
    "Classic diabetes symptoms present but no laboratory data available. Urgently obtain: (1) Fasting plasma glucose. (2) HbA1c. (3) Random plasma glucose if fasting not possible. These tests are required for definitive diagnosis.": "Your symptoms are the classic diabetes signs, but a blood test is still needed to confirm. Book one this week — it takes minutes.",
    "Multiple diabetes-associated symptoms detected (neuropathy signs + frequent infections). Priority laboratory testing recommended: HbA1c and fasting glucose within 1 week.": "Nerve tingling plus repeated infections suggests long-standing high sugar. Do an HbA1c and fasting glucose test within 1 week.",
    "Young patient with overweight/obesity and diabetes risk factors. ADA recommends screening regardless of age when BMI ≥25 with risk factors. Complete fasting glucose and HbA1c testing.": "Young with overweight plus risk factors still deserves a check. A fasting glucose or HbA1c test now sets your baseline.",
    "Very high diabetes risk: Prior gestational diabetes + current obesity. Recommend: (1) Annual HbA1c and fasting glucose screening. (2) Target ≥7% weight loss. (3) ≥150 min/week moderate exercise. (4) Consider metformin for prevention (ADA grade A recommendation).": "Prior gestational diabetes with overweight is a high-risk combination. Annual sugar checks, about 7% weight loss and regular movement strongly cut the risk.",
    "EMERGENCY: Level 3 severe hypoglycemia (<40 mg/dL). Call emergency services immediately. Administer glucagon if available. Do NOT attempt to give oral glucose if patient is unconscious or unable to swallow safely.": "EMERGENCY: severe low blood sugar. Call emergency services now. If unconscious, never give food or drink by mouth.",
    "Diabetic neuropathy likely: Tingling extremities with confirmed hyperglycemia. Urgent referrals needed: (1) Comprehensive foot examination with monofilament testing. (2) Nerve conduction study. (3) Tight glycemic control to prevent progression. (4) Neuropathic pain management if symptomatic.": "Nerve signs with confirmed high sugar mean early diabetic neuropathy. You need a foot exam and steadier sugar control — see your doctor within 2 weeks.",
    "High compound risk identified (smoking + obesity + family history). Urgent recommendations: (1) Smoking cessation program. (2) Weight management target 5-10% reduction. (3) Annual HbA1c and lipid monitoring. (4) CardioVascular risk assessment. (5) Consider aspirin therapy if CVD risk >10%.": "Smoking, weight and family history multiply each other's risk. Quitting smoking is the single biggest step — then weight, movement and yearly checks.",
    "PCOS + prediabetes: Accelerated diabetes risk. Recommend: (1) Metformin therapy (addresses both PCOS and diabetes prevention). (2) Weight management. (3) HbA1c monitoring every 6 months. (4) Endocrine referral for comprehensive PCOS management.": "PCOS with prediabetes speeds up diabetes risk. Metformin helps both; recheck HbA1c every 6 months and ask for a PCOS care plan.",
    "Hidden diabetes pattern detected (tingling + frequent infections + fatigue). This combination suggests possible longstanding undiagnosed diabetes. Priority: Obtain HbA1c, fasting glucose, and complete blood count. Schedule comprehensive foot and neurological exam.": "Tingling, infections and fatigue together can hide long-standing high sugar. Get HbA1c, fasting glucose and a basic check-up soon.",
    "PCOS + obesity: Elevated metabolic risk. Recommendations: (1) Annual OGTT preferred over HbA1c (PCOS affects HbA1c accuracy). (2) Lipid panel and liver function tests. (3) Weight management with target 5-10% reduction. (4) Screen for obstructive sleep apnea. (5) Consider myo-inositol supplementation.": "With PCOS and overweight, aim for 5–10% weight loss and yearly glucose checks — an OGTT is often preferred with PCOS.",
    "Young adult with diabetes risk factors. Prevention plan: (1) Target BMI <25 through sustainable lifestyle changes. (2) 150-300 min/week of moderate-to-vigorous exercise. (3) Limit added sugars and ultra-processed foods. (4) Annual fasting glucose and HbA1c screening. (5) Consider genetic counseling if strong family history.": "A great time to prevent: keep BMI under 25, move 150–300 minutes a week, limit sugary and ultra-processed food, and check sugars yearly.",
    "Your fasting glucose and HbA1c are both within normal ranges. No diabetes or prediabetes detected at this time. Continue healthy lifestyle habits and schedule routine screening as recommended by your doctor.": "Both blood tests are normal — no diabetes detected today. Keep your healthy habits and re-screen as your doctor advises.",
    "Your fasting glucose is within the normal range. Continue maintaining a healthy lifestyle. If you have risk factors (family history, obesity, etc.), schedule HbA1c testing for a more complete assessment.": "Your fasting glucose is normal. Keep your lifestyle, and if you carry risk factors an HbA1c test adds a fuller picture.",
    "Prediabetes with classic diabetes symptoms detected. This combination suggests faster progression risk. Recommendations: (1) Repeat fasting glucose and HbA1c in 1–3 months (not 6 months). (2) Begin intensive lifestyle intervention immediately. (3) Discuss metformin with your doctor. (4) Monitor symptoms closely.": "Prediabetes plus symptoms means faster progression risk. Re-test in 1–3 months instead of 6, and start lifestyle changes now.",
    "Diabetes confirmed by all three diagnostic criteria (FPG, HbA1c, OGTT). Immediate action: (1) Schedule endocrinology or primary care appointment within 1-2 weeks. (2) Begin diabetes self-management education. (3) Comprehensive screening for complications (eyes, feet, kidneys, cardiovascular). (4) Treatment initiation based on clinical presentation.": "All three lab criteria confirm diabetes. Book a clinic visit within 1–2 weeks to start treatment and complication screening.",
    "Your lab values are currently normal, but you report symptoms associated with diabetes. Recommendations: (1) Repeat fasting glucose in 1–3 months. (2) Request HbA1c if not already tested. (3) Consider OGTT for more sensitive detection. (4) Investigate other potential causes of your symptoms with your doctor. (5) Monitor symptom changes.": "Your blood tests look normal today, but your symptoms are still classic diabetes signs — symptoms can appear before blood sugar rises. Keep watching them and re-test in 1–3 months.",
    "Your fasting glucose is in the high-normal range (95-99 mg/dL). While technically normal, this is approaching the prediabetes threshold. Proactive steps: (1) Adopt a low-glycemic diet. (2) Regular physical activity. (3) Re-test in 6-12 months to track trends.": "Your fasting glucose is in the upper-normal range (95–99) — close to the prediabetes line. A lower-sugar diet, regular movement, and a re-test in 6–12 months will track the trend.",
    "OGTT result combined with classic symptoms strongly indicates diabetes. Please schedule a comprehensive diabetes evaluation within 1-2 weeks. Treatment initiation should not be delayed.": "The glucose test plus classic symptoms strongly indicates diabetes. Book a full diabetes evaluation within 1–2 weeks — treatment should not wait.",
    "Diabetes confirmed. Your comprehensive care plan should include: (1) Individualized HbA1c target (generally <7% for most adults, <6.5% if low hypoglycemia risk). (2) Metformin as first-line therapy unless contraindicated. (3) SGLT2 inhibitor or GLP-1 receptor agonist if cardiovascular or renal disease risk. (4) Retinal screening within 5 years (or at diagnosis for T2D). (5) Annual foot exam and vaccination schedule. (6) Lipid panel — statin therapy if indicated. (7) Blood pressure target <130/80 mmHg. (8) Diabetes self-management education. (9) Psychological well-being assessment. (10) Ongoing HbA1c monitoring every 3 months until stable, then every 6 months.": "Diabetes confirmed. Your care plan: sugar targets, metformin first (usually), eye and foot checks, blood pressure and cholesterol care, and diabetes education — start within 1–2 weeks.",
    "Pregnancy detected. Screen for gestational diabetes with a 75g OGTT (ideally between weeks 24-28; earlier if risk factors such as prior GDM, obesity, or family history are present). Pregnancy glucose thresholds are stricter: fasting >= 92 mg/dL, 1h >= 180 mg/dL, or 2h >= 153 mg/dL on OGTT indicates GDM (IADPSG criteria).": "Pregnancy detected. Gestational diabetes screening with a 75 g OGTT is advised — ideally between weeks 24–28, earlier if you have risk factors.",
    "Fasting glucose meets pregnancy thresholds for gestational diabetes (>= 92 mg/dL per IADPSG). Schedule obstetric review within 1 week. Management starts with diet and glucose monitoring; insulin if targets are not met. Untreated GDM increases risks of macrosomia, pre-eclampsia, and neonatal hypoglycemia.": "Your fasting glucose crosses the stricter pregnancy threshold. See your obstetric team within 1 week — diet and glucose monitoring come first, insulin only if needed.",
    "OGTT result meets pregnancy thresholds for gestational diabetes (2h >= 153 mg/dL per IADPSG). Schedule obstetric review within 1 week for confirmation and a management plan.": "Your OGTT crosses the pregnancy threshold for gestational diabetes. See your obstetric team within 1 week to confirm and plan.",
    "Prior gestational diabetes with current pregnancy: arrange glucose testing at the first prenatal visit (not only at weeks 24-28), plus lifestyle counselling. Recurrence risk is high (30-70%).": "Prior gestational diabetes in this pregnancy: glucose testing at the first prenatal visit (not only weeks 24–28) — recurrence risk is high.",
    "New bed-wetting with increased urination in a child is a diabetes red flag. Arrange same-day clinical review with a finger-prick glucose test.": "New bed-wetting with extra urination in a child is a red flag for type 1 diabetes. Get a finger-prick glucose check today.",
    "Recurrent infections with elevated glucose suggest glucose-driven infection risk. Treat the infection and improve glycemic control — discuss with the clinical team.": "High sugar feeds infections. Treating the infection and lowering sugar work together — discuss both with your care team.",
    "Sudden onset with weight loss fits a Type 1 pattern. This can progress to diabetic ketoacidosis quickly — urgent same-week medical review is required, do not wait for routine appointments.": "Sudden symptoms with weight loss fit the type 1 pattern — it can worsen within days. Get a medical review this week; do not wait for a routine appointment.",
    "Ketosis signs with high blood glucose can indicate DKA. Seek emergency care now — do not wait for lab confirmation.": "Ketone signs with high blood sugar can mean DKA. Seek emergency care now — do not wait for lab confirmation.",
    "Lean body habitus with catabolic weight loss is atypical for Type 2. Ask the clinician about autoantibody (GAD) and C-peptide testing to distinguish Type 1 / LADA.": "A lean body with rapid weight loss is unusual for type 2. Ask about GAD-antibody and C-peptide tests — they separate type 1/LADA from type 2.",
    "The evidence pattern mixes features of Type 1 and Type 2. Ask about autoantibody (GAD) and C-peptide testing — overlapping presentations such as LADA are easily missed and are treated differently.": "Your signs mix type 1 and type 2 features. Ask about GAD-antibody and C-peptide testing — overlapping patterns are treated differently.",
    "Diabetes confirmed by concordant laboratory criteria. \" \"Please schedule an appointment with your physician within 1–2 weeks for: \" \"(1) Individualized HbA1c target setting. \" \"(2) First-line therapy initiation (typically metformin). \" \"(3) Retinal screening referral. \" \"(4) Comprehensive foot examination. \" \"(5) Lipid panel and cardiovascular risk assessment. \" \"(6) Diabetes self-management education enrollment.": "Diabetes is confirmed by two matching tests. Book your doctor within 1–2 weeks: sugar targets, metformin first (usually), plus eye and foot checks.",
    "Your test results are consistent with diabetes. \" \"A confirmatory test is recommended unless you have unequivocal hyperglycemia symptoms. \" \"Please see your healthcare provider within 1–2 weeks for confirmation and treatment planning.": "Your results fit diabetes. A quick confirmatory test plus a doctor visit within 1–2 weeks settles it and starts treatment.",
    "Some of your results suggest possible diabetes, but a definitive diagnosis requires additional testing. \" \"Please schedule a follow-up within 2–4 weeks for: \" \"(1) Fasting plasma glucose or HbA1c confirmation. \" \"(2) Complete metabolic panel if not already done.": "Some results suggest possible diabetes. A fasting glucose or HbA1c test within 2–4 weeks will settle it.",
    "Your results fall in the prediabetes range. This is an important window for prevention. \" \"Evidence-based recommendations: \" \"(1) Aim for ≥7% body weight loss through diet and exercise. \" \"(2) At least 150 minutes per week of moderate physical activity (e.g., brisk walking). \" \"(3) Limit refined carbohydrates and added sugars. \" \"(4) Repeat HbA1c and fasting glucose in 3–6 months. \" \"(5) Consider enrollment in a Diabetes Prevention Program (DPP).": "Prediabetes — a warning stage you can reverse. Lose about 7% of body weight, move 150 minutes a week, cut sugary drinks, and re-test in 3–6 months.",
    "You have prediabetes combined with additional risk factors, putting you at high risk for progression to diabetes. \" \"Intensive intervention recommended: \" \"(1) Structured lifestyle modification program. \" \"(2) Target ≥7% weight loss. \" \"(3) ≥150 min/week moderate exercise. \" \"(4) Discuss metformin with your doctor for chemoprevention (especially if BMI ≥35 or age <60). \" \"(5) Repeat testing every 6 months.": "Prediabetes with extra risk factors — act now: structured lifestyle change, ask your doctor about metformin, and re-check every 6 months.",
    "You have classic diabetes symptoms (increased urination, excessive thirst, unexplained weight loss). \" \"These warrant urgent laboratory testing: \" \"(1) Fasting plasma glucose. \" \"(2) HbA1c. \" \"(3) Random plasma glucose if fasting not possible. \" \"Please see a healthcare provider within 1 week.": "Your symptoms are the classic diabetes signs, but a blood test is still needed to confirm. Book one this week — it takes minutes.",
    "You have diabetes-related symptoms but no laboratory data was available. \" \"Symptoms alone cannot confirm or rule out diabetes. \" \"Priority action: Obtain fasting glucose and HbA1c within 1 week for definitive assessment.": "Your answers match common diabetes signs. A simple blood test (fasting glucose or HbA1c) will confirm — any lab, results usually the same day.",
    "Signs of possible neuropathy have been detected. \" \"This may indicate longstanding undiagnosed diabetes. Recommended evaluations: \" \"(1) Comprehensive foot exam with monofilament testing. \" \"(2) HbA1c and fasting glucose (if not already done). \" \"(3) Nerve conduction study if symptoms persist. \" \"(4) Please see your doctor within 2 weeks.": "Nerve signs with confirmed high sugar mean early diabetic neuropathy. You need a foot exam and steadier sugar control — see your doctor within 2 weeks.",
    "Your profile is consistent with metabolic syndrome — a cluster of conditions \" \"that significantly increase cardiovascular and diabetes risk. Recommendations: \" \"(1) Blood pressure monitoring and control (target <130/80 mmHg). \" \"(2) Lipid management (consider statin therapy if LDL elevated). \" \"(3) Weight management (target 5–10% reduction). \" \"(4) Regular physical activity. \" \"(5) Annual cardiovascular risk assessment.": "Your blood pressure, weight and cholesterol pattern raise heart and diabetes risk. Move more, eat plainer, and treat blood pressure and cholesterol with your doctor.",
    "You have one or more risk factors for Type 2 diabetes. \" \"Preventive recommendations: \" \"(1) Maintain a healthy weight (BMI <25). \" \"(2) Exercise at least 150 minutes per week. \" \"(3) Follow a balanced diet rich in whole grains, vegetables, and lean proteins. \" \"(4) Routine diabetes screening every 3 years (or annually if prediabetes identified). \" \"(5) Discuss family history and personal risk with your healthcare provider.": "You carry type 2 risk factors. Keep a healthy weight, move 150 minutes a week, eat more whole foods, and screen every 1–3 years.",
    "Based on your age and demographic profile, routine diabetes screening is recommended. \" \"Please schedule: Fasting glucose or HbA1c test. \" \"If results are normal, repeat every 3 years.": "Routine check: one fasting glucose or HbA1c test now — repeat every 3 years if normal.",
    "Good news — your assessment shows no indication of diabetes or prediabetes at this time. \" \"To maintain your health: \" \"(1) Continue a balanced diet and regular physical activity. \" \"(2) Schedule routine health check-ups as recommended by your doctor. \" \"(3) If you develop new symptoms (excessive thirst, frequent urination, unexplained weight loss), \" \"seek medical evaluation promptly.": "Good news — no signs of diabetes today. Keep your habits, re-screen routinely, and come back if new symptoms appear.",
    "Your assessment did not reveal strong indicators of diabetes. \" \"Continue routine health monitoring and maintain a healthy lifestyle. \" \"If new symptoms develop, consult your healthcare provider.": "No strong diabetes signs in this assessment. Keep healthy routines and re-check if anything changes.",
    # v2 rule seed (app.utils.diabetes_rule_seed_data_v2)
    "Test results meet the diabetes diagnostic threshold. See a healthcare provider promptly to start treatment and a monitoring plan — bring these results with you.": "Your test results meet the diabetes threshold. See a doctor soon to start treatment and a monitoring plan — bring these results with you.",
}


def _normalize_key(text: str) -> str:
    return " ".join(str(text or "").split())


def rewrite_recommendation(text: str) -> str:
    """Return the patient-friendly text for a known clinical string."""
    key = _normalize_key(text)
    return RECOMMENDATION_REWRITES.get(key, key)

