/**
 * Symptom media registry for the assessment interview.
 * Maps assessment question nodes and symptom field keys to clinical reference images,
 * medical terms, and bilingual clinical clues.
 */

export const SYMPTOM_MEDIA_MAP = {
  excessive_thirst: {
    key: 'excessive_thirst',
    image: '/images/png/thirsty.png',
    fallbackImage: '/images/png/thirsty.png',
    medicalTerm: 'Polydipsia',
    nameEn: 'Excessive Thirst',
    nameKm: 'ស្រេកទឹកខ្លាំងមិនបាត់',
    captionEn: 'Persistent dry mouth and unquenchable thirst even after drinking high volumes of fluids.',
    captionKm: 'អារម្មណ៍ស្រេកទឹកខ្លាំងផឹកមិនចេះឆ្អែត ជាញឹកញាប់កើតឡើងជាមួយមាត់ស្ងួត។',
    badgeEn: 'Cardinal Sign',
    badgeKm: 'សញ្ញាសំខាន់',
  },
  frequent_urination: {
    key: 'frequent_urination',
    image: '/images/png/urination.png',
    fallbackImage: '/images/png/urination.png',
    medicalTerm: 'Polyuria',
    nameEn: 'Frequent Urination',
    nameKm: 'នោមញឹកញាប់ ជាពិសេសពេលយប់',
    captionEn: 'Needing to pass urine more often than normal, waking 2+ times at night (Nocturia).',
    captionKm: 'ការបន្ទោរបង់ទឹកនោមញឹកញាប់ជាងធម្មតា ជាពិសេសក្រោកនោមច្រើនដងនៅពេលយប់។',
    badgeEn: 'Cardinal Sign',
    badgeKm: 'សញ្ញាសំខាន់',
  },
  excessive_hunger: {
    key: 'excessive_hunger',
    image: '/images/png/excessive-hunger.png',
    fallbackImage: '/images/png/excessive-hunger.png',
    medicalTerm: 'Polyphagia',
    nameEn: 'Constant Hunger',
    nameKm: 'ឃ្លានបាយជាប់រហូត',
    captionEn: 'Intense hunger pangs and cravings even immediately after eating full meals.',
    captionKm: 'អារម្មណ៍ឃ្លានខ្លាំងជាប់រហូត ទោះបីជាទើបតែញ៉ាំបាយឆ្អែតក៏ដោយ។',
    badgeEn: 'Cardinal Sign',
    badgeKm: 'សញ្ញាសំខាន់',
  },
  weight_loss: {
    key: 'weight_loss',
    image: '/images/png/weight-loss.png',
    fallbackImage: '/images/png/weight-loss.png',
    medicalTerm: 'Unexplained Weight Loss',
    nameEn: 'Rapid Weight Loss',
    nameKm: 'ស្រកទម្ងន់លឿនដោយមិនដឹងមូលហេតុ',
    captionEn: 'Noticeable drop in body weight despite normal or increased food intake.',
    captionKm: 'ការស្រកទម្ងន់ចុះយ៉ាងលឿន ទោះបីជាញ៉ាំបាយធម្មតា ឬញ៉ាំច្រើនជាងមុនក៏ដោយ។',
    badgeEn: 'Cardinal Sign',
    badgeKm: 'សញ្ញាសំខាន់',
  },
  fatigue: {
    key: 'fatigue',
    image: '/images/png/fatigue.png',
    fallbackImage: '/images/png/fatigue.png',
    medicalTerm: 'Asthenia / Exhaustion',
    nameEn: 'Persistent Fatigue',
    nameKm: 'អស់កម្លាំង ល្វើយ គ្មានកម្លាំងកំហែង',
    captionEn: 'Feeling drained, sluggish, and physically exhausted not relieved by sleep.',
    captionKm: 'មានអារម្មណ៍អស់កម្លាំង ល្វើយ ងងុយគេងជាប់រហូត ទោះបីជាបានគេងពេញលេញក៏ដោយ។',
    badgeEn: 'Cardinal Sign',
    badgeKm: 'សញ្ញាសំខាន់',
  },
  blurred_vision: {
    key: 'blurred_vision',
    image: '/images/png/blur.png',
    fallbackImage: '/images/png/blur.png',
    medicalTerm: 'Osmotic Lens Swelling',
    nameEn: 'Blurred Vision',
    nameKm: 'ភ្នែកស្រវាំង មើលមិនសូវច្បាស់',
    captionEn: 'Hazy or unfocused eyesight that fluctuates with shifting blood glucose levels.',
    captionKm: 'ភ្នែកស្រវាំង មើលអ្វីៗមិនច្បាស់ ដែលអាចប្រែប្រួលតាមកម្រិតជាតិស្ករ។',
    badgeEn: 'Microvascular Sign',
    badgeKm: 'សញ្ញាសរសៃឈាមតូច',
  },
  tingling_hands_feet: {
    key: 'tingling_hands_feet',
    image: '/images/png/tingling.png',
    fallbackImage: '/images/png/tingling.png',
    medicalTerm: 'Paresthesia / Neuropathy',
    nameEn: 'Tingling Hands & Feet',
    nameKm: 'ស្ពឹក ឬស្រពន់ចុងដៃចុងជើង',
    captionEn: 'Pins-and-needles, prickling, or numbness in the fingers, toes, or feet.',
    captionKm: 'អារម្មណ៍ដូចមានម្ជុលចាក់ ឬស្រពន់នៅចុងម្រាមដៃ និងចុងម្រាមជើង។',
    badgeEn: 'Nerve Warning Sign',
    badgeKm: 'សញ្ញាប្រព័ន្ធប្រសាទ',
  },
  burning_sensation: {
    key: 'burning_sensation',
    image: '/images/png/burning-feet.png',
    fallbackImage: '/images/png/burning-feet.png',
    medicalTerm: 'Neuropathic Pain',
    nameEn: 'Burning Feet / Legs',
    nameKm: 'អារម្មណ៍ក្តៅក្រហាយនៅបាតជើង',
    captionEn: 'Hot, stinging, or painful burning sensations in the feet and calves, often worse at night.',
    captionKm: 'មានអារម្មណ៍ក្តៅក្រហាយ ឈឺចាប់ដូចត្រូវភ្លើងរោលនៅបាតជើង ឬជើង ជាពិសេសពេលយប់។',
    badgeEn: 'Nerve Warning Sign',
    badgeKm: 'សញ្ញាប្រព័ន្ធប្រសាទ',
  },
  slow_healing: {
    key: 'slow_healing',
    image: '/images/png/slow-healing.png',
    fallbackImage: '/images/png/slow-healing.png',
    medicalTerm: 'Impaired Healing',
    nameEn: 'Slow Wound Healing',
    nameKm: 'ដំបៅ ឬរបួសក្រសះស្បើយ',
    captionEn: 'Minor cuts, blisters, or skin scrapes that linger for weeks or easily get infected.',
    captionKm: 'ដំបៅតូចតាច ឬស្នាមមុតដែលចំណាយពេលយូរខុសធម្មតាទើបជាសះស្បើយ។',
    badgeEn: 'Vascular Sign',
    badgeKm: 'សញ្ញាសរសៃឈាម',
  },
  acanthosis_nigricans: {
    key: 'acanthosis_nigricans',
    image: '/images/png/dark-skin.png',
    fallbackImage: '/images/png/dark-skin.png',
    medicalTerm: 'Acanthosis Nigricans',
    nameEn: 'Dark Velvety Skin Patches',
    nameKm: 'ស្បែកឡើងខ្មៅក្រាស់នៅកញ្ចឹងក ឬក្លៀក',
    captionEn: 'Dark, velvety hyperpigmentation in skin creases (neck folds, axillae, knuckles) from insulin resistance.',
    captionKm: 'ស្បែកឡើងខ្មៅក្រាស់ដូចកម្ញី នៅត្រង់ផ្នត់ក ក្លៀក ឬគន្លាក់ដៃជើង (សញ្ញាស៊ាំអាំងស៊ុយលីន)។',
    badgeEn: 'Insulin Resistance',
    badgeKm: 'សញ្ញាស៊ាំអាំងស៊ុយលីន',
  },
  bed_wetting: {
    key: 'bed_wetting',
    image: '/images/png/bed-wetting.png',
    fallbackImage: '/images/png/bed-wetting.png',
    medicalTerm: 'Nocturnal Enuresis',
    nameEn: 'New Bed-Wetting',
    nameKm: 'នោមដាក់ពូកពេលយប់លើកុមារ',
    captionEn: 'Sudden onset of bed-wetting in a previously continent child; primary pediatric T1D signal.',
    captionKm: 'កុមារដែលធ្លាប់ចេះបត់ជើង ស្រាប់តែចាប់ផ្តើមនោមដាក់ពូកវិញពេលយប់។',
    badgeEn: 'Pediatric Red Flag',
    badgeKm: 'សញ្ញាអាសន្នលើកុមារ',
  },
  recurrent_uti_yeast: {
    key: 'recurrent_uti_yeast',
    image: '/images/png/frequent-infections.png',
    fallbackImage: '/images/png/frequent-infections.png',
    medicalTerm: 'Candidiasis / Recurrent UTI',
    nameEn: 'Frequent Infections',
    nameKm: 'ការឆ្លងមេរោគផ្សិត ឬផ្លូវទឹកនោមញឹកញាប់',
    captionEn: 'Persistent or recurring fungal yeast infections or UTIs fueled by high urinary glucose.',
    captionKm: 'ការឆ្លងមេរោគផ្សិត ឬរលាកផ្លូវទឹកនោមញឹកញាប់ដែលពិបាកព្យាបាល។',
    badgeEn: 'Immune & Glycemic Sign',
    badgeKm: 'សញ្ញាប្រព័ន្ធភាពស៊ាំ',
  },
  frequent_infections: {
    key: 'frequent_infections',
    image: '/images/png/frequent-infections.png',
    fallbackImage: '/images/png/frequent-infections.png',
    medicalTerm: 'Candidiasis / Recurrent Infections',
    nameEn: 'Frequent Infections',
    nameKm: 'ការឆ្លងមេរោគញឹកញាប់',
    captionEn: 'Persistent skin, fungal, or urinary infections fueled by elevated blood glucose.',
    captionKm: 'ការឆ្លងមេរោគលើស្បែក ផ្សិត ឬផ្លូវទឹកនោមញឹកញាប់ដោយសារជាតិស្ករក្នុងឈាមខ្ពស់។',
    badgeEn: 'Immune & Glycemic Sign',
    badgeKm: 'សញ្ញាប្រព័ន្ធភាពស៊ាំ',
  },
  fruity_breath: {
    key: 'fruity_breath',
    image: '/images/symptoms/fruity_breath.jpg',
    fallbackImage: '/images/symptoms/fruity_breath.jpg',
    medicalTerm: 'Acetone / Ketone Breath',
    nameEn: 'Fruity Acetone Breath',
    nameKm: 'ដង្ហើមមានក្លិនផ្លែឈើ ឬក្លិនអាសេតូន',
    captionEn: 'Sweet, fruity, or nail-polish-remover odor on breath indicating blood ketone buildup.',
    captionKm: 'ដង្ហើមមានក្លិនផ្អែម ឬដូចទឹកលាងថ្នាំក្រចក (សញ្ញាអាសន្ន DKA)។',
    badgeEn: 'DKA Emergency Sign',
    badgeKm: 'សញ្ញាសង្គ្រោះបន្ទាន់ DKA',
  },
  deep_rapid_breathing: {
    key: 'deep_rapid_breathing',
    image: '/images/png/deep-breathing.png',
    fallbackImage: '/images/png/deep-breathing.png',
    medicalTerm: 'Kussmaul Respiration',
    nameEn: 'Deep Rapid Breathing',
    nameKm: 'ដកដង្ហើមញាប់ និងជ្រៅៗខុសធម្មតា',
    captionEn: 'Abnormally deep, labored breathing as the body attempts to compensate for acidosis.',
    captionKm: 'ការដកដង្ហើមញាប់ និងជ្រៅៗខ្លាំង ដោយសាររាងកាយព្យាយាមបញ្ចេញជាតិអាស៊ីត។',
    badgeEn: 'DKA Emergency Sign',
    badgeKm: 'សញ្ញាសង្គ្រោះបន្ទាន់ DKA',
  },
  waist_circumference: {
    key: 'waist_circumference',
    image: '/images/png/waist-measurement.png',
    fallbackImage: '/images/png/waist-measurement.png',
    medicalTerm: 'Central Adiposity / Abdominal Fat',
    nameEn: 'Waist Circumference',
    nameKm: 'ទំហំរង្វង់ចង្កេះ',
    captionEn: 'Measured below the ribs, usually at the level of the navel. A strong independent risk factor for metabolic syndrome and type 2 diabetes.',
    captionKm: 'វាស់នៅខាងក្រោមឆ្អឹងជំនីរ ត្រឹមកម្រិតផ្ចិត។ ជាកត្តាហានិភ័យឯករាជ្យដ៏សំខាន់នៃជំងឺទឹកនោមផ្អែមប្រភេទទី 2។',
    badgeEn: 'Metabolic Risk',
    badgeKm: 'ហានិភ័យមេតាបូលិក',
  },
  bmiscale: {
    key: 'bmiscale',
    image: '/images/png/bmiscale.png',
    fallbackImage: '/images/png/bmiscale.png',
    medicalTerm: 'Body Mass Index',
    nameEn: 'Body Mass Index',
    nameKm: 'សន្ទស្សន៍ម៉ាសរាងកាយ',
    captionEn: 'Body mass index assesses whether a person is normal weight, overweight, or obese.',
    captionKm: 'សន្ទស្សន៍ម៉ាសរាងកាយវាយតម្លៃថាតើមនុស្សម្នាក់មានទម្ងន់ធម្មតា លើសទម្ងន់ ឬធាត់។',
    badgeEn: 'Clinical Reference',
    badgeKm: 'ឯកសារយោងវេជ្ជសាស្ត្រ',
  },
  clinical_consultation: {
    key: 'clinical_consultation',
    image: '/images/png/bmi-consultation.png',
    fallbackImage: '/images/png/bmi-consultation.png',
    medicalTerm: 'Clinical Assessment',
    nameEn: 'Clinical Assessment',
    nameKm: 'ការវាយតម្លៃគ្លីនិក',
    captionEn: 'Comprehensive clinical evaluation and evidence screening.',
    captionKm: 'ការវាយតម្លៃ និងពិនិត្យគ្លីនិកគ្រប់ជ្រុងជ្រោយ។',
    badgeEn: 'Assessment',
    badgeKm: 'ការវាយតម្លៃ',
  },
  family_history: {
    key: 'family_history',
    image: '/images/png/family.png',
    fallbackImage: '/images/png/family.png',
    medicalTerm: 'Familial Predisposition',
    nameEn: 'Family History of Diabetes',
    nameKm: 'ប្រវត្តិគ្រួសារមានជំងឺទឹកនោមផ្អែម',
    captionEn: 'Having a first-degree relative (parent or sibling) with diabetes doubles baseline risk.',
    captionKm: 'ការមានឪពុកម្តាយ ឬបងប្អូនបង្កើតដែលមានជំងឺទឹកនោមផ្អែម បង្កើនហានិភ័យទ្វេដង។',
    badgeEn: 'Genetic Factor',
    badgeKm: 'កត្តាតំណពូជ',
  },
  hypertension: {
    key: 'hypertension',
    image: '/images/png/blood-pressure.png',
    fallbackImage: '/images/png/blood-pressure.png',
    medicalTerm: 'Essential Hypertension',
    nameEn: 'Elevated Blood Pressure',
    nameKm: 'សម្ពាធឈាមឡើងខ្ពស់',
    captionEn: 'Blood pressure ≥130/80 mmHg or taking antihypertensive medication.',
    captionKm: 'សម្ពាធឈាមចាប់ពី ១៣០/៨០ mmHg ឬកំពុងប្រើប្រាស់ថ្នាំបញ្ចុះសម្ពាធឈាម។',
    badgeEn: 'Cardiovascular Risk',
    badgeKm: 'ហានិភ័យសរសៃឈាមបេះដូង',
  },
  physical_activity: {
    key: 'physical_activity',
    image: '/images/png/physical-activity.png',
    fallbackImage: '/images/png/physical-activity.png',
    medicalTerm: 'Physical Activity & Inactivity',
    nameEn: 'Physical Activity Level',
    nameKm: 'កម្រិតសកម្មភាពរាងកាយ',
    captionEn: 'ADA clinical guidelines recommend at least 150 minutes of moderate-to-vigorous exercise weekly.',
    captionKm: 'ការណែនាំគ្លីនិកណែនាំយ៉ាងហោចណាស់ ១៥០ នាទីនៃលំហាត់ប្រាណមធ្យមក្នុងមួយសប្តាហ៍។',
    badgeEn: 'Lifestyle Factor',
    badgeKm: 'កត្តារបៀបរស់នៅ',
  },
  sugary_diet: {
    key: 'sugary_diet',
    image: '/images/png/sugary-drinks-food.png',
    fallbackImage: '/images/png/sugary-drinks-food.png',
    medicalTerm: 'High Glycemic Load',
    nameEn: 'Sugary Drinks & Sweets',
    nameKm: 'ភេសជ្ជៈផ្អែម និងអាហារម្សៅកែច្នៃ',
    captionEn: 'Frequent consumption of soda, sweet tea, energy drinks, and refined pastries.',
    captionKm: 'ការទទួលទានទឹកក្រូចផ្អែម តែផ្អែម និងបង្អែមញឹកញាប់ដែលបង្កើនជាតិស្ករក្នុងឈាមលឿន។',
    badgeEn: 'Dietary Factor',
    badgeKm: 'កត្តារបបអាហារ',
  },
  lab_result: {
    key: 'lab_result',
    image: '/images/png/lab-result.png',
    fallbackImage: '/images/png/lab-result.png',
    medicalTerm: 'Glycemic Biomarkers',
    nameEn: 'Laboratory Blood Tests',
    nameKm: 'លទ្ធផលតេស្តឈាមមន្ទីរពិសោធន៍',
    captionEn: 'Fasting blood glucose, HbA1c glycated hemoglobin, and 2-hour OGTT metrics.',
    captionKm: 'លទ្ធផលជាតិស្ករពេលព្រឹកព្រលឹម តម្លៃ HbA1c និងតេស្តផ្ទុកជាតិស្ករ OGTT។',
    badgeEn: 'Diagnostic Gold Standard',
    badgeKm: 'ស្តង់ដាររោគវិនិច្ឆ័យ',
  },
}

/* Node ID aliases mapped to symptom media */
export const NODE_MEDIA_MAP = {
  subject: 'clinical_consultation',
  patient: 'clinical_consultation',
  age: 'clinical_consultation',
  sex: 'clinical_consultation',
  ethnicity: 'clinical_consultation',
  body: 'bmiscale',
  waist: 'waist_circumference',
  waist_circumference: 'waist_circumference',
  symptom_thirst: 'excessive_thirst',
  thirst_probe: 'excessive_thirst',
  symptom_urination: 'frequent_urination',
  nocturia_probe: 'frequent_urination',
  symptom_hunger: 'excessive_hunger',
  symptom_weight_loss: 'weight_loss',
  symptom_fatigue: 'fatigue',
  fatigue_probe: 'fatigue',
  child_probe: 'bed_wetting',
  family_history: 'family_history',
  blood_pressure: 'hypertension',
  lifestyle_diet: 'sugary_diet',
  lifestyle_activity: 'physical_activity',
  sedentary_lifestyle: 'physical_activity',
  physical_activity_minutes_week: 'physical_activity',
  frequent_infections: 'frequent_infections',
  recurrent_uti_yeast: 'frequent_infections',
  has_labs: 'lab_result',
  labs: 'lab_result',
}

/**
 * Returns the symptom media object for an interview node, or null if none.
 */
export function getNodeSymptomMedia(node, language = 'en') {
  if (!node) return null
  const mediaKey = NODE_MEDIA_MAP[node.id] || (node.field && SYMPTOM_MEDIA_MAP[node.field] ? node.field : null)
  if (!mediaKey || !SYMPTOM_MEDIA_MAP[mediaKey]) return null

  const item = SYMPTOM_MEDIA_MAP[mediaKey]
  const isKm = language === 'km'
  return {
    key: item.key,
    image: item.image,
    fallbackImage: item.fallbackImage,
    medicalTerm: item.medicalTerm,
    name: isKm && item.nameKm ? item.nameKm : item.nameEn,
    caption: isKm && item.captionKm ? item.captionKm : item.captionEn,
    badge: isKm && item.badgeKm ? item.badgeKm : item.badgeEn,
  }
}

/**
 * Returns symptom media for an individual symptom field key.
 */
export function getFieldSymptomMedia(fieldKey, language = 'en') {
  if (!fieldKey || !SYMPTOM_MEDIA_MAP[fieldKey]) return null
  const item = SYMPTOM_MEDIA_MAP[fieldKey]
  const isKm = language === 'km'
  return {
    key: item.key,
    image: item.image,
    fallbackImage: item.fallbackImage,
    medicalTerm: item.medicalTerm,
    name: isKm && item.nameKm ? item.nameKm : item.nameEn,
    caption: isKm && item.captionKm ? item.captionKm : item.captionEn,
    badge: isKm && item.badgeKm ? item.badgeKm : item.badgeEn,
  }
}
