"""Structured starter rule set for the diabetes expert system."""

DIABETES_RULE_SEED = [
    {
        "code": "triage-hypoglycemia-threshold",
        "name": "Triage hypoglycemia threshold",
        "description": "Detects low blood glucose requiring immediate action.",
        "category": "triage",
        "priority": "high",
        "certainty_factor": 0.95,
        "status": "active",
        "explanation_text": "Blood glucose below 70 mg/dL is a low-sugar alert threshold.",
        "conditions": [
            {"fact_key": "blood_glucose", "operator": "<", "expected_value": 70},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "hypoglycemia=true"},
            {"action_type": "assert_fact", "action_value": "take_action_now=true"},
            {
                "action_type": "recommendation",
                "action_value": "Take fast-acting glucose now and recheck sugar promptly.",
            },
        ],
    },
    {
        "code": "triage-symptomatic-hypoglycemia-sweating",
        "name": "Triage symptomatic hypoglycemia (sweating)",
        "description": "Flags symptomatic hypoglycemia pattern when sweating is present.",
        "category": "triage",
        "priority": "high",
        "certainty_factor": 0.88,
        "status": "active",
        "explanation_text": "Sweating with hypoglycemia suggests symptomatic low blood sugar.",
        "conditions": [
            {"fact_key": "hypoglycemia", "operator": "==", "expected_value": True},
            {"fact_key": "sweating", "operator": "==", "expected_value": True, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "symptomatic_hypoglycemia=true"},
        ],
    },
    {
        "code": "triage-symptomatic-hypoglycemia-shaking",
        "name": "Triage symptomatic hypoglycemia (shaking)",
        "description": "Flags symptomatic hypoglycemia pattern when shaking is present.",
        "category": "triage",
        "priority": "high",
        "certainty_factor": 0.88,
        "status": "active",
        "explanation_text": "Shaking with hypoglycemia suggests symptomatic low blood sugar.",
        "conditions": [
            {"fact_key": "hypoglycemia", "operator": "==", "expected_value": True},
            {"fact_key": "shaking", "operator": "==", "expected_value": True, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "symptomatic_hypoglycemia=true"},
        ],
    },
    {
        "code": "triage-symptomatic-hypoglycemia-dizziness",
        "name": "Triage symptomatic hypoglycemia (dizziness)",
        "description": "Flags symptomatic hypoglycemia pattern when dizziness is present.",
        "category": "triage",
        "priority": "high",
        "certainty_factor": 0.86,
        "status": "active",
        "explanation_text": "Dizziness with hypoglycemia suggests symptomatic low blood sugar.",
        "conditions": [
            {"fact_key": "hypoglycemia", "operator": "==", "expected_value": True},
            {"fact_key": "dizziness", "operator": "==", "expected_value": True, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "symptomatic_hypoglycemia=true"},
        ],
    },
    {
        "code": "triage-possible-dka-cluster",
        "name": "Triage possible DKA symptom cluster",
        "description": "Flags possible DKA when hyperglycemia is combined with vomiting and abdominal pain.",
        "category": "triage",
        "priority": "high",
        "certainty_factor": 0.93,
        "status": "active",
        "explanation_text": "Hyperglycemia with vomiting and abdominal pain can indicate possible DKA.",
        "conditions": [
            {"fact_key": "hyperglycemia_present", "operator": "==", "expected_value": True},
            {"fact_key": "vomiting", "operator": "==", "expected_value": True, "logical_operator": "and"},
            {"fact_key": "abdominal_pain", "operator": "==", "expected_value": True, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "possible_dka=true"},
            {"action_type": "urgent_flag", "action_value": "true"},
        ],
    },
    {
        "code": "triage-classic-symptom-cluster",
        "name": "Triage classic hyperglycemia symptom cluster",
        "description": "Identifies classic symptom pattern of frequent urination, excessive thirst, and weight loss.",
        "category": "triage",
        "priority": "medium",
        "certainty_factor": 0.76,
        "status": "active",
        "explanation_text": "Classic symptom cluster increases suspicion for diabetes-related hyperglycemia.",
        "conditions": [
            {"fact_key": "frequent_urination", "operator": "==", "expected_value": True},
            {"fact_key": "excessive_thirst", "operator": "==", "expected_value": True, "logical_operator": "and"},
            {"fact_key": "weight_loss", "operator": "==", "expected_value": True, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "classic_hyperglycemia_symptoms=true"},
            {"action_type": "assert_fact", "action_value": "classic_symptom_cluster=true"},
            {"action_type": "diagnosis_conclusion", "action_value": "classic_symptoms"},
        ],
    },
    {
        "code": "diagnosis-fasting-glucose-threshold",
        "name": "Diagnosis fasting plasma glucose threshold",
        "description": "Applies diabetes diagnostic threshold using fasting plasma glucose.",
        "category": "diagnosis",
        "priority": "high",
        "certainty_factor": 0.9,
        "status": "active",
        "explanation_text": "Fasting glucose at or above 126 mg/dL supports diabetes diagnosis criteria.",
        "conditions": [
            {"fact_key": "fasting_glucose", "operator": ">=", "expected_value": 126},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "diabetes_diagnostic_criterion_met=true"},
            {"action_type": "diagnosis_conclusion", "action_value": "diabetes_possible"},
        ],
    },
    {
        "code": "diagnosis-hba1c-threshold",
        "name": "Diagnosis HbA1c threshold",
        "description": "Applies diabetes diagnostic threshold using HbA1c.",
        "category": "diagnosis",
        "priority": "high",
        "certainty_factor": 0.93,
        "status": "active",
        "explanation_text": "HbA1c at or above 6.5% indicates chronic hyperglycemia consistent with diabetes.",
        "conditions": [
            {"fact_key": "hba1c", "operator": ">=", "expected_value": 6.5},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "diabetes_diagnostic_criterion_met=true"},
            {"action_type": "diagnosis_conclusion", "action_value": "diabetes_likely"},
        ],
    },
    {
        "code": "diagnosis-random-glucose-classic-symptoms",
        "name": "Diagnosis random glucose with classic symptoms",
        "description": "Supports likely diabetes when random glucose is high with classic hyperglycemia symptoms.",
        "category": "diagnosis",
        "priority": "high",
        "certainty_factor": 0.9,
        "status": "active",
        "explanation_text": "Random plasma glucose above threshold plus classic symptoms suggests likely diabetes.",
        "conditions": [
            {"fact_key": "random_plasma_glucose", "operator": ">=", "expected_value": 200},
            {"fact_key": "classic_hyperglycemia_symptoms", "operator": "==", "expected_value": True, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "diabetes_diagnostic_criterion_met=true"},
            {"action_type": "diagnosis_conclusion", "action_value": "diabetes_likely"},
        ],
    },
    {
        "code": "diagnosis-prediabetes-fasting-range",
        "name": "Diagnosis prediabetes fasting range",
        "description": "Detects prediabetes range using fasting glucose values.",
        "category": "diagnosis",
        "priority": "medium",
        "certainty_factor": 0.7,
        "status": "active",
        "explanation_text": "Fasting glucose between 100 and 125 mg/dL supports prediabetes.",
        "conditions": [
            {"fact_key": "fasting_glucose", "operator": ">=", "expected_value": 100},
            {"fact_key": "fasting_glucose", "operator": "<=", "expected_value": 125, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "prediabetes_possible=true"},
            {"action_type": "diagnosis_conclusion", "action_value": "prediabetes_possible"},
        ],
    },
    {
        "code": "diagnosis-prediabetes-hba1c-range",
        "name": "Diagnosis prediabetes HbA1c range",
        "description": "Detects prediabetes range using HbA1c values.",
        "category": "diagnosis",
        "priority": "medium",
        "certainty_factor": 0.72,
        "status": "active",
        "explanation_text": "HbA1c between 5.7% and 6.4% supports prediabetes.",
        "conditions": [
            {"fact_key": "hba1c", "operator": ">=", "expected_value": 5.7},
            {"fact_key": "hba1c", "operator": "<=", "expected_value": 6.4, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "prediabetes_possible=true"},
            {"action_type": "diagnosis_conclusion", "action_value": "prediabetes_possible"},
        ],
    },
    {
        "code": "diagnosis-prediabetes-ogtt-range",
        "name": "Diagnosis prediabetes OGTT range",
        "description": "Detects prediabetes range using 2-hour OGTT values.",
        "category": "diagnosis",
        "priority": "medium",
        "certainty_factor": 0.72,
        "status": "active",
        "explanation_text": "2-hour OGTT between 140 and 199 mg/dL supports prediabetes.",
        "conditions": [
            {"fact_key": "2h_ogtt_75g", "operator": ">=", "expected_value": 140},
            {"fact_key": "2h_ogtt_75g", "operator": "<=", "expected_value": 199, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "prediabetes_possible=true"},
            {"action_type": "diagnosis_conclusion", "action_value": "prediabetes_possible"},
        ],
    },
    {
        "code": "classification-type2-risk-bmi-family-history",
        "name": "Classification type 2 risk pattern (BMI + family history)",
        "description": "Classifies high type 2 risk pattern from BMI and family history.",
        "category": "classification",
        "priority": "medium",
        "certainty_factor": 0.74,
        "status": "active",
        "explanation_text": "Increased BMI plus family history is a common type 2 diabetes risk pattern.",
        "conditions": [
            {"fact_key": "bmi", "operator": ">=", "expected_value": 25},
            {"fact_key": "family_history", "operator": "==", "expected_value": True, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "type2_risk_increased=true"},
            {"action_type": "assert_fact", "action_value": "high_type2_risk_pattern=true"},
        ],
    },
    {
        "code": "classification-type2-risk-bmi-activity",
        "name": "Classification type 2 risk pattern (BMI + low activity)",
        "description": "Classifies high type 2 risk pattern from BMI and low physical activity.",
        "category": "classification",
        "priority": "medium",
        "certainty_factor": 0.72,
        "status": "active",
        "explanation_text": "Increased BMI with low activity increases type 2 diabetes risk.",
        "conditions": [
            {"fact_key": "bmi", "operator": ">=", "expected_value": 25},
            {"fact_key": "sedentary_lifestyle", "operator": "==", "expected_value": True, "logical_operator": "and"},
        ],
        "actions": [
            {"action_type": "assert_fact", "action_value": "type2_risk_increased=true"},
            {"action_type": "assert_fact", "action_value": "high_type2_risk_pattern=true"},
        ],
    },
    {
        "code": "recommendation-urgent-dka-referral",
        "name": "Recommendation urgent DKA referral",
        "description": "Escalates to urgent referral when DKA pattern is detected.",
        "category": "recommendation",
        "priority": "high",
        "certainty_factor": 0.95,
        "status": "active",
        "explanation_text": "Possible DKA requires emergency medical evaluation.",
        "conditions": [
            {"fact_key": "possible_dka", "operator": "==", "expected_value": True},
        ],
        "actions": [
            {"action_type": "urgent_flag", "action_value": "true"},
            {
                "action_type": "recommendation",
                "action_value": "Go to emergency care now for possible diabetic ketoacidosis assessment.",
            },
        ],
    },
    {
        "code": "recommendation-hypoglycemia-follow-up",
        "name": "Recommendation hypoglycemia follow-up",
        "description": "Provides immediate low-sugar correction and follow-up guidance.",
        "category": "recommendation",
        "priority": "high",
        "certainty_factor": 0.9,
        "status": "active",
        "explanation_text": "Symptomatic hypoglycemia requires immediate correction and medication review.",
        "conditions": [
            {"fact_key": "symptomatic_hypoglycemia", "operator": "==", "expected_value": True},
        ],
        "actions": [
            {
                "action_type": "recommendation",
                "action_value": "Treat low sugar immediately and arrange prompt clinical follow-up.",
            },
        ],
    },
    {
        "code": "recommendation-prediabetes-lifestyle-followup",
        "name": "Recommendation prediabetes lifestyle follow-up",
        "description": "Provides preventive follow-up recommendation for possible prediabetes.",
        "category": "recommendation",
        "priority": "medium",
        "certainty_factor": 0.78,
        "status": "active",
        "explanation_text": "Prediabetes patterns should be followed with lifestyle support and repeat testing.",
        "conditions": [
            {"fact_key": "prediabetes_possible", "operator": "==", "expected_value": True},
        ],
        "actions": [
            {
                "action_type": "recommendation",
                "action_value": "Start lifestyle intervention and repeat diabetes screening within 3 months.",
            },
        ],
    },
    {
        "code": "recommendation-diabetes-clinical-referral",
        "name": "Recommendation diabetes clinical referral",
        "description": "Advises formal clinical evaluation when diabetes criterion is met.",
        "category": "recommendation",
        "priority": "high",
        "certainty_factor": 0.84,
        "status": "active",
        "explanation_text": "Objective diabetes criteria should be confirmed and managed by a clinician.",
        "conditions": [
            {"fact_key": "diabetes_diagnostic_criterion_met", "operator": "==", "expected_value": True},
        ],
        "actions": [
            {
                "action_type": "recommendation",
                "action_value": "Arrange clinical diabetes evaluation and confirmatory testing if required.",
            },
        ],
    },
    {
        "code": "recommendation-limited-evidence-lab-completion",
        "name": "Recommendation limited evidence lab completion",
        "description": "Prompts laboratory completion in screening-only assessments.",
        "category": "recommendation",
        "priority": "medium",
        "certainty_factor": 0.72,
        "status": "active",
        "explanation_text": "Without lab values, confidence is limited and lab completion is recommended.",
        "conditions": [
            {"fact_key": "no_lab_values_available", "operator": "==", "expected_value": True},
        ],
        "actions": [
            {
                "action_type": "recommendation",
                "action_value": "Complete fasting glucose and HbA1c tests to improve assessment reliability.",
            },
        ],
    },
]
