# -*- coding: utf-8 -*-
"""Doctor-manageable fact/symptom knowledge catalog - seed data.

Every entry is a fact key the inference engine and interview exchange
(symptoms, risk factors, labs, profile flags). Each row carries:

- patient-facing education: label / label_km / medical_term / meaning / meaning_km / prevention / prevention_km
- interview questions: question
- reasoning inputs: weight, type_indication, is_cardinal, is_emergency, aliases, display_order

All 51 facts have complete English and Khmer labels, clinical explanations (meaning),
and actionable prevention and management guidance.
"""

FACT_CATALOG_SEED = [
    {
        'key': 'excessive_hunger',
        'label': 'Excessive Hunger',
        'label_km': 'ហៀរស្រេកអាហារខ្លាំង',
        'medical_term': 'Polyphagia',
        'category': 'cardinal',
        'question': 'Do you feel hungry all the time, even after eating?',
        'question_km': 'តើអ្នកមានអារម្មណ៍ឃ្លានបាយខ្លាំងខុសធម្មតា ឬឃ្លានអាហារជាប់រហូត ទោះបីជាទើបតែញ៉ាំបាយឆ្អែតក៏ដោយ?',
        'meaning': 'Can occur when glucose cannot effectively enter cells.',
        'meaning_km': 'អាចកើតឡើងពេលជាតិស្ករចូលទៅក្នុងក្រឡាក្រូបសាចមិនបាន។',
        'prevention': 'Eat balanced meals with fibre and protein so energy is released slowly.',
        'prevention_km': 'ទទួលទានអាហារពេញលេញដែលមានជាតិសរសៃ និងប្រូតេអ៊ីន ដើម្បីឱ្យថាមពលបញ្ចេញបន្តិចម្តងៗ។',
        'weight': 0.25,
        'type_indication': 'both',
        'is_cardinal': True,
        'is_emergency': False,
        'aliases': ['polyphagia'],
        'display_order': 10,
    },
    {
        'key': 'excessive_thirst',
        'label': 'Excessive Thirst',
        'label_km': 'ស្រេកទឹកខ្លាំង',
        'medical_term': 'Polydipsia',
        'category': 'cardinal',
        'question': 'Do you feel unusually thirsty, even after drinking water?',
        'question_km': 'តើអ្នកមានអារម្មណ៍ស្រេកទឹកខ្លាំងខុសធម្មតា ឬស្រេកមិនចេះបាត់ ទោះបីជាផឹកទឹករួចហើយក៏ដោយ?',
        'meaning': 'Can occur when blood glucose is high — the body pulls water to dilute the sugar.',
        'meaning_km': 'អាចកើតឡើងពេលជាតិស្ករក្នុងឈាមខ្ពស់ — រាងកាយទាញទឹកដើម្បីបន្ថយប្រភេទស្ករ។',
        'prevention': 'Drink water regularly and keep blood sugar in the target range; avoid sugary drinks.',
        'prevention_km': 'ផឹកទឹកឱ្យបានទៀងទាត់ និងរក្សាជាតិស្ករក្នុងឈាមឱ្យនៅកម្រិតគោលដៅ។ ជៀសវាងភេសជ្ជៈមានជាតិស្ករ។',
        'weight': 0.3,
        'type_indication': 'both',
        'is_cardinal': True,
        'is_emergency': False,
        'aliases': ['polydipsia'],
        'display_order': 20,
    },
    {
        'key': 'frequent_urination',
        'label': 'Frequent Urination',
        'label_km': 'នោមញឹកញាប់',
        'medical_term': 'Polyuria',
        'category': 'cardinal',
        'question': 'Do you need to urinate more often than usual, especially at night?',
        'question_km': 'តើអ្នកត្រូវបត់ជើងតូច (នោម) ញឹកញាប់ជាងធម្មតា ជាពិសេសភ្ញាក់នោមច្រើនដងនៅពេលយប់ដែរឬទេ?',
        'meaning': 'Often accompanies high blood glucose — the kidneys flush out the extra sugar.',
        'meaning_km': 'ភាគច្រើនមកជាមួយជាតិស្ករខ្ពស់ — តណ្ហាប្រឹងប្រែងបញ្ចេញស្ករលើសទៅក្រៅ។',
        'prevention': 'Limit caffeine in the evening and keep glucose well controlled to reduce night-time trips.',
        'prevention_km': 'កាត់បន្ថយជាតិកាហ្វេពេលល្ងាច និងគ្រប់គ្រងជាតិស្ករឱ្យបានល្អ ដើម្បីបន្ថយការភ្ញាក់ពេលយប់។',
        'weight': 0.3,
        'type_indication': 'both',
        'is_cardinal': True,
        'is_emergency': False,
        'aliases': ['polyuria'],
        'display_order': 30,
    },
    {
        'key': 'fatigue',
        'label': 'Extreme Fatigue',
        'label_km': 'អស់កម្លាំងប្រចាំ',
        'medical_term': 'Asthenia',
        'category': 'metabolic',
        'question': 'Do you feel unusually tired or exhausted, even after rest?',
        'question_km': 'តើអ្នកមានអារម្មណ៍អស់កម្លាំង ល្វើយខ្លាំងប្រចាំថ្ងៃ ដែលការគេងមិនអាចជួយឱ្យស្រឡះបានដែរឬទេ?',
        'meaning': "Cells don't get enough glucose for energy.",
        'meaning_km': 'ក្រឡាក្រូបសាចមិនទទួលបានជាតិស្ករគ្រប់គ្រាន់ដើម្បីបង្កើតថាមពល។',
        'prevention': 'Light regular exercise, good sleep and steady meals help restore energy.',
        'prevention_km': 'លំហាត់ប្រាណស្រាលៗជាប្រចាំ ការគេងគ្រប់គ្រាន់ និងអាហារទៀងទាត់ ជួយបង្កើនថាមពលវិញ។',
        'weight': 0.15,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['extreme_fatigue'],
        'display_order': 40,
    },
    {
        'key': 'increased_appetite',
        'label': 'Increased Appetite Despite Eating',
        'label_km': 'ឃ្លានអាហារខ្លាំងខុសធម្មតា',
        'medical_term': 'Hyperphagia',
        'category': 'metabolic',
        'question': 'Do you eat more than usual but still feel hungry?',
        'question_km': 'តើអ្នកញ៉ាំច្រើនជាងធម្មតា ប៉ុន្តែនៅតែមានអារម្មណ៍ឃ្លានជាប់រហូតឬ?',
        'meaning': 'Can occur when body cells cannot absorb glucose from the blood due to insulin deficiency or resistance, signaling constant hunger.',
        'meaning_km': 'អាចកើតឡើងនៅពេលកោសិកាមិនអាចស្រូបយកជាតិស្ករពីឈាមបាន ដោយសារកង្វះ ឬភាពធន់នឹងអាំងស៊ុយលីន ដែលធ្វើឱ្យរាងកាយមានអារម្មណ៍ឃ្លានជានិច្ច។',
        'prevention': 'Eat balanced meals rich in dietary fibre and lean protein, drink water before meals, and monitor blood glucose to ensure proper insulin action.',
        'prevention_km': 'ទទួលទានអាហារសម្បូរជាតិសរសៃ និងប្រូតេអ៊ីន ផឹកទឹកមុនពេលបាយ និងតាមដានជាតិស្ករក្នុងឈាមដើម្បីឱ្យអាំងស៊ុយលីនដំណើរការល្អ។',
        'weight': 0.15,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['hyperphagia'],
        'display_order': 50,
    },
    {
        'key': 'weakness',
        'label': 'General Weakness',
        'label_km': 'ការចុះខ្សោយកម្លាំងទូទៅ',
        'medical_term': 'Generalized asthenia',
        'category': 'metabolic',
        'question': 'Do you feel weak or lack energy to do daily activities?',
        'question_km': 'តើអ្នកមានអារម្មណ៍អស់កម្លាំង ល្ហិតល្ហៃ ឬខ្វះថាមពលក្នុងការបំពេញសកម្មភាពប្រចាំថ្ងៃឬ?',
        'meaning': 'Without sufficient glucose entering muscle cells, the muscles cannot generate power, leading to generalized physical weakness.',
        'meaning_km': 'បើគ្មានជាតិស្ករគ្រប់គ្រាន់ចូលក្នុងកោសិកាសាច់ដុំទេ សាច់ដុំមិនអាចបង្កើតថាមពលបានឡើយ ដែលបណ្តាលឱ្យចុះខ្សោយកម្លាំងទូទៅ។',
        'prevention': 'Balance physical activity with appropriate nutrition, stay hydrated, and maintain blood glucose levels within the target range.',
        'prevention_km': 'រក្សាតុល្យភាពរវាងសកម្មភាពរាងកាយ និងអាហារូបត្ថម្ភត្រឹមត្រូវ ផឹកទឹកឱ្យគ្រប់គ្រាន់ និងរក្សាកម្រិតជាតិស្ករក្នុងកម្រិតគោលដៅ។',
        'weight': 0.12,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['general_weakness'],
        'display_order': 60,
    },
    {
        'key': 'weight_loss',
        'label': 'Unexplained Weight Loss',
        'label_km': 'ស្រកទម្ងន់ដោយមិនដឹងមូលហេតុ',
        'medical_term': 'Catabolic weight loss',
        'category': 'metabolic',
        'question': 'Have you lost weight without trying or without changing your diet?',
        'question_km': 'តើអ្នកបានស្រកទម្ងន់គួរឱ្យកត់សម្គាល់ដោយមិនបានតមអាហារ ឬមិនដឹងមូលហេតុដែរឬទេ?',
        'meaning': "The body burns fat and muscle for energy when glucose can't enter cells.",
        'meaning_km': 'រាងកាយដុតខ្លាញ់និងសាច់ដុំជំនួសថាមពល ពេលជាតិស្ករចូលក្រឡាក្រូបមិនបាន។',
        'prevention': 'See a doctor soon — sudden weight loss needs checking; balanced meals help rebuild healthy weight.',
        'prevention_km': 'ទៅជួបវេជ្ជបណ្ឌិតឱ្យឆាប់ — ការស្រកទម្ងន់ភ្លាមៗត្រូវការពិនិត្យ។ អាហារពេញលេញជួយសាងសង់ទម្ងន់ដែលមានសុខភាពល្អវិញ។',
        'weight': 0.25,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['unexplained_weight_loss'],
        'display_order': 70,
    },
    {
        'key': 'blurred_vision',
        'label': 'Blurred Vision',
        'label_km': 'ការស្រវាំងភ្នែក',
        'medical_term': 'Lens swelling',
        'category': 'vision',
        'question': 'Is your vision blurry or have you noticed changes in your eyesight?',
        'question_km': 'តើភ្នែករបស់អ្នកមើលឃើញព្រាលៗ ឬមានការប្រែប្រួលគំហើញដែរឬទេ?',
        'meaning': "High glucose draws water into the eye's lens, blurring focus.",
        'meaning_km': 'ជាតិស្ករខ្ពស់ទាញទឹកចូលត្រឡប់ភ្នែក ធ្វើឱ្យមើលមិនច្បាស់។',
        'prevention': 'Bring glucose back to target and get an eye exam — vision usually improves as sugar stabilises.',
        'prevention_km': 'នាំជាតិស្ករត្រឡប់មកកម្រិតគោលដៅវិញ និងពិនិត្យភ្នែក — ការមើលឃើញភាគច្រើនប្រសើរឡើងវិញពេលជាតិស្ករមានស្ថិរភាព។',
        'weight': 0.18,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['blurry_vision'],
        'display_order': 80,
    },
    {
        'key': 'difficulty_seeing',
        'label': 'Difficulty Seeing at Night',
        'label_km': 'ពិបាកមើលឃើញនៅពេលយប់',
        'medical_term': 'Nyctalopia',
        'category': 'vision',
        'question': 'Do you have trouble seeing clearly, especially in dim light or at night?',
        'question_km': 'តើអ្នកមានការពិបាកមើលឃើញច្បាស់ ជាពិសេសនៅកន្លែងខ្សោយពន្លឺ ឬនៅពេលយប់ឬ?',
        'meaning': 'Fluctuating blood glucose levels can cause retinal microvascular changes and lens swelling, impairing vision in dim lighting.',
        'meaning_km': 'ការប្រែប្រួលកម្រិតជាតិស្ករក្នុងឈាមអាចបណ្តាលឱ្យសរសៃឈាមតូចៗនៅបាតភ្នែករងការប៉ះពាល់ និងប៉ោងកែវភ្នែក ធ្វើឱ្យពិបាកមើលក្នុងទីងងឹត។',
        'prevention': 'Schedule annual dilated retinal eye exams, keep blood glucose and blood pressure stable, and wear protective eyewear in bright sun.',
        'prevention_km': 'ពិនិត្យបាតភ្នែកជារៀងរាល់ឆ្នាំជាមួយគ្រូពេទ្យភ្នែក រក្សាជាតិស្ករ និងសម្ពាធឈាមឱ្យមានស្ថិរភាព និងពាក់វ៉ែនតាការពារពន្លឺ។',
        'weight': 0.1,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['night_vision_difficulty'],
        'display_order': 90,
    },
    {
        'key': 'acanthosis_nigricans',
        'label': 'Acanthosis Nigricans',
        'label_km': 'ស្បែកខ្មៅក្រាស់នៅកញ្ចឹងកឬក្លៀក',
        'medical_term': 'Acanthosis nigricans',
        'category': 'skin',
        'question': 'Do you have dark, velvety patches of skin, especially on your neck or armpits?',
        'question_km': 'តើអ្នកមានស្នាមអុចខ្មៅ ឬស្បែកឡើងក្រាស់ខ្មៅជ្រួញៗនៅជុំវិញក ឬក្លៀកដែរឬទេ?',
        'meaning': 'Dark, velvety skin patches — commonly linked with insulin resistance.',
        'meaning_km': 'ស្បែកខ្មៅជ្រួញៗ — ភាគច្រើនទាក់ទងនឹង insulin resistance។',
        'prevention': 'Weight loss and exercise often fade these patches — ask a doctor about insulin resistance.',
        'prevention_km': 'ការបន្ថយទម្ងន់ និងការហាត់ប្រាណជារឿយៗជួយបន្ថយស្នាមខ្មៅៗទាំងនេះ — សួរវេជ្ជបណ្ឌិតអំពីភាពធន់ទ្រាំ insulin។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 100,
    },
    {
        'key': 'frequent_infections',
        'label': 'Frequent Infections',
        'label_km': 'ឆ្លងរោគញឹកញាប់',
        'medical_term': 'Recurrent infections',
        'category': 'skin',
        'question': 'Do you get frequent infections (skin, gum, bladder, or yeast infections)?',
        'question_km': 'តើអ្នកឧស្សាហ៍ឆ្លងមេរោគ (ស្បែក ជើងធ្មេញ ប្លោកនោម ឬផ្សិត) ញឹកញាប់ដែរឬទេ?',
        'meaning': "High glucose weakens the immune system's defences.",
        'meaning_km': 'ជាតិស្ករខ្ពស់ចុះខ្សោយប្រព័ន្ធភាពការពាររាងកាយ។',
        'prevention': 'Keep glucose in range, keep skin clean and dry, and treat infections early.',
        'prevention_km': 'រក្សាជាតិស្ករឱ្យនៅកម្រិតគោលដៅ រក្សាស្បែកស្អាតនិងស្ងួត និងព្យាបាលការឆ្លងទាន់ពេល។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['recurrent_infections'],
        'display_order': 110,
    },
    {
        'key': 'itchy_skin',
        'label': 'Itchy or Dry Skin',
        'label_km': 'ស្បែកស្ងួត ឬរមាស់',
        'medical_term': 'Pruritus cutis',
        'category': 'skin',
        'question': 'Do you suffer from unusually dry or persistently itchy skin?',
        'question_km': 'តើអ្នកមានស្បែកស្ងួតខ្លាំង ឬរមាស់ជាប់រហូតដែរឬទេ?',
        'meaning': 'High blood sugar dehydrates the body and impairs peripheral blood flow, leading to chronic skin dryness and itching.',
        'meaning_km': 'ជាតិស្ករខ្ពស់ធ្វើឱ្យរាងកាយបាត់បង់ជាតិទឹក និងកាត់បន្ថយលំហូរឈាមទៅស្បែក ដែលនាំឱ្យស្បែកស្ងួត និងរមាស់រ៉ាំរ៉ៃ។',
        'prevention': 'Moisturize skin with gentle unscented lotion, avoid very hot showers, stay well-hydrated, and keep blood glucose in target.',
        'prevention_km': 'ប្រើឡេផ្តល់សំណើមស្បែកដែលគ្មានក្លិនក្រអូប ជៀសវាងងូតទឹកក្តៅពេក ផឹកទឹកឱ្យបានច្រើន និងគ្រប់គ្រងជាតិស្ករឱ្យបានល្អ។',
        'weight': 0.08,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['dry_itchy_skin'],
        'display_order': 120,
    },
    {
        'key': 'slow_healing',
        'label': 'Slow Healing Cuts/Bruises',
        'label_km': 'របួសជាសះស្បើយយឺត',
        'medical_term': 'Impaired wound healing',
        'category': 'skin',
        'question': 'Do cuts, bruises, or sores take longer than usual to heal?',
        'question_km': 'តើរបួស ដំបៅ ឬស្នាមជាំរបស់អ្នកត្រូវការពេលយូរខុសធម្មតាដើម្បីជាសះស្បើយដែរឬទេ?',
        'meaning': 'High glucose slows blood flow and weakens immune repair.',
        'meaning_km': 'ជាតិស្ករខ្ពស់បន្ថយដំណើរឈាមវិញភាគ និងចុះខ្សោយភាពការពាររាងកាយ។',
        'prevention': 'Clean and protect wounds early and keep glucose in range to speed up healing.',
        'prevention_km': 'សម្អាត និងការពាររបួសទាន់ពេល និងរក្សាជាតិស្ករឱ្យនៅកម្រិតគោលដៅ ដើម្បីឱ្យរបួសជាសះស្បើយលឿនជាង។',
        'weight': 0.18,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['slow_healing_wounds'],
        'display_order': 130,
    },
    {
        'key': 'erectile_dysfunction',
        'label': 'Erectile Dysfunction',
        'label_km': 'បញ្ហាខ្សោយសមត្ថភាពផ្លូវភេទ',
        'medical_term': 'Diabetic erectile dysfunction',
        'category': 'reproductive',
        'question': 'Have you noticed persistent difficulty achieving or maintaining an erection?',
        'question_km': 'តើអ្នកមានបញ្ហាខ្សោយសមត្ថភាពផ្លូវភេទ ឬពិបាកក្នុងការឡើងរឹងជាប់រហូតឬ?',
        'meaning': 'Prolonged hyperglycemia can damage autonomic nerves and microvascular blood vessels that regulate genital blood circulation.',
        'meaning_km': 'ជាតិស្ករខ្ពស់ក្នុងឈាមរយៈពេលយូរអាចបំផ្លាញសរសៃប្រសាទ និងសរសៃឈាមតូចៗដែលផ្គត់ផ្គង់ចរន្តឈាមទៅប្រដាប់បន្តពូជ។',
        'prevention': 'Maintain tight glycemic, blood pressure and lipid control, avoid smoking, exercise regularly, and consult a physician early.',
        'prevention_km': 'គ្រប់គ្រងកម្រិតជាតិស្ករ សម្ពាធឈាម និងខ្លាញ់ឱ្យបានល្អ ឈប់ជក់បារី ហាត់ប្រាណទៀងទាត់ និងពិគ្រោះជាមួយគ្រូពេទ្យឱ្យបានទាន់ពេល។',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['ed'],
        'display_order': 140,
    },
    {
        'key': 'yeast_infections',
        'label': 'Recurrent Yeast Infections',
        'label_km': 'ការឆ្លងរោគផ្សិតម្តងហើយម្តងទៀត',
        'medical_term': 'Candidiasis',
        'category': 'reproductive',
        'question': 'Do you experience frequent genital or skin fold yeast infections?',
        'question_km': 'តើអ្នកឧស្សាហ៍កើតរោគផ្សិតនៅតំបន់ប្រដាប់ភេទ ឬផ្នត់ស្បែកញឹកញាប់ឬ?',
        'meaning': 'Elevated glucose in sweat, urine, and mucosal secretions creates an ideal environment for Candida albicans fungus to overgrow.',
        'meaning_km': 'ជាតិស្ករលើសនៅក្នុងញើស ទឹកនោម និងភ្នាសរំអិល បង្កើតបរិយាកាសល្អសម្រាប់ពពួកផ្សិត Candida រីកលូតលាស់យ៉ាងលឿន។',
        'prevention': 'Keep blood sugar in target range, wear breathable cotton undergarments, keep skin folds dry, and complete prescribed antifungal treatments.',
        'prevention_km': 'រក្សាជាតិស្ករក្នុងឈាមឱ្យនៅកម្រិតធម្មតា ស្លៀកសម្លៀកបំពាក់កប្បាសដែលមានខ្យល់ចេញចូល រក្សាស្បែកឱ្យស្ងួត និងលេបថ្នាំផ្សិតតាមវេជ្ជបញ្ជា។',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 150,
    },
    {
        'key': 'difficulty_concentrating',
        'label': 'Difficulty Concentrating',
        'label_km': 'ពិបាកផ្ចង់អារម្មណ៍ ឬខួរក្បាលស្រពិចស្រពិល',
        'medical_term': 'Diabetic brain fog',
        'category': 'mental',
        'question': 'Do you find it harder than usual to concentrate, think clearly, or stay focused?',
        'question_km': 'តើអ្នកពិបាកផ្ចង់អារម្មណ៍ គិតមិនសូវច្បាស់ ឬពិបាកក្នុងការផ្តោតលើការងារជាងធម្មតាឬ?',
        'meaning': 'Rapid spikes or drops in blood glucose disrupt brain neurotransmitter balance and cellular energy delivery, impairing concentration.',
        'meaning_km': 'ការកើនឡើង ឬធ្លាក់ចុះលឿននៃជាតិស្ករក្នុងឈាមរំខានដល់តុល្យភាពសារធាតុបញ្ជូនសរសៃប្រសាទ និងថាមពលខួរក្បាល ធ្វើឱ្យពិបាកផ្ចង់អារម្មណ៍។',
        'prevention': 'Maintain consistent meal timing, avoid large simple-sugar loads, sleep 7–8 hours, and test blood sugar when concentration drops.',
        'prevention_km': 'ទទួលទានអាហារឱ្យទៀងពេល ជៀសវាងអាហារផ្អែមខ្លាំង គេងឱ្យបាន ៧-៨ ម៉ោង និងពិនិត្យជាតិស្ករពេលមានអារម្មណ៍មិនសូវផ្ចង់។',
        'weight': 0.08,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['brain_fog'],
        'display_order': 160,
    },
    {
        'key': 'irritability',
        'label': 'Irritability Or Mood Changes',
        'label_km': 'អាក់អន់ចិត្ត / ប្រែប្រួលអារម្មណ៍',
        'medical_term': 'Mood lability',
        'category': 'mental',
        'question': 'Have you been more irritable or experienced mood swings?',
        'question_km': 'តើអ្នកឆាប់ខឹង មួរម៉ៅ ឬមានការប្រែប្រួលអារម្មណ៍ញឹកញាប់ខុសធម្មតាឬ?',
        'meaning': 'Blood sugar swings can affect mood and concentration.',
        'meaning_km': 'ជាតិស្ករឡើងចុះអាចប៉ះពាល់អារម្មណ៍និងការផ្ចង់អារម្មណ៍។',
        'prevention': 'Steady meals, sleep and glucose control can lift mood — seek support if it persists.',
        'prevention_km': 'អាហារទៀងទាត់ ការគេងគ្រប់គ្រាន់ និងការគ្រប់គ្រងជាតិស្ករ អាចធ្វើឱ្យអារម្មណ៍ប្រសើរ — សុំការជួយប្រសិនបើវាបន្តយូរ។',
        'weight': 0.08,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['mood_swings'],
        'display_order': 170,
    },
    {
        'key': 'abdominal_pain',
        'label': 'Abdominal Pain',
        'label_km': 'ឈឺពោះខ្លាំង',
        'medical_term': 'Acute abdominal pain',
        'category': 'emergency',
        'question': 'Do you have severe stomach pain, cramping, or abdominal tenderness?',
        'question_km': 'តើអ្នកមានការឈឺពោះធ្ងន់ធ្ងរ រមួលក្រពះ ឬឈឺចុកចាប់ក្នុងពោះឬ?',
        'meaning': 'With very high glucose this can signal DKA — seek care urgently.',
        'meaning_km': 'ពេលជាតិស្ករខ្ពស់ខ្លាំងអាចជាសញ្ញា DKA — ទៅពេទ្យបន្ទាន់។',
        'prevention': 'Get medical help promptly, especially with vomiting or high sugar — possible DKA.',
        'prevention_km': 'ទៅរកជំនួយវេជ្ជសាស្ត្រឱ្យឆាប់ ជាពិសេសពេលក្អួត ឬជាតិស្ករខ្ពស់ — អាចជា DKA។',
        'weight': 0.15,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 180,
    },
    {
        'key': 'confusion',
        'label': 'Sudden Confusion / Disorientation',
        'label_km': 'វង្វេងស្មារតីភ្លាមៗ',
        'medical_term': 'Acute neuroglycopenia',
        'category': 'emergency',
        'question': 'Are you or the patient experiencing acute confusion, slurred speech, or disorientation?',
        'question_km': 'តើអ្នក ឬអ្នកជំងឺកំពុងមានការវង្វេងវង្វាន់ និយាយមិនច្បាស់ ឬមិនដឹងទិសតំបន់ឬ?',
        'meaning': 'A critical sign of severe neuroglycopenia (dangerously low glucose <54 mg/dL) or severe metabolic crisis (DKA/HHS).',
        'meaning_km': 'សញ្ញាគ្រោះថ្នាក់នៃការធ្លាក់ចុះជាតិស្ករធ្ងន់ធ្ងរ (<54 mg/dL) ឬវិបត្តិមេតាបូលីសធ្ងន់ធ្ងរ (DKA ឬ HHS) ដែលប៉ះពាល់ដល់មុខងារខួរក្បាល។',
        'prevention': 'Immediately administer fast-acting sugar if conscious; if unresponsive or glucose is critical high, seek emergency medical care immediately.',
        'prevention_km': 'ផ្តល់ជាតិស្កររលាយលឿនភ្លាមៗប្រសិនបើនៅដឹងខ្លួន បើបាត់បង់ស្មារតីត្រូវបញ្ជូនទៅសង្គ្រោះបន្ទាន់នៅមន្ទីរពេទ្យជាបន្ទាន់។',
        'weight': 0.25,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': True,
        'aliases': ['disorientation'],
        'display_order': 190,
    },
    {
        'key': 'crisis',
        'label': 'Diabetic Metabolic Crisis (DKA/HHS)',
        'label_km': 'វិបត្តិជាតិស្ករធ្ងន់ធ្ងរ (DKA / HHS)',
        'medical_term': 'Diabetic ketoacidosis / Hyperosmolar state',
        'category': 'emergency',
        'question': 'Are there critical warning signs such as severe vomiting, labored breathing, extreme confusion, or collapse?',
        'question_km': 'តើមានសញ្ញាអាសន្នធ្ងន់ធ្ងរដូចជា ក្អួតខ្លាំង ពិបាកដកដង្ហើម វង្វេងស្មារតី ឬដួលសន្លប់ឬ?',
        'meaning': 'A life-threatening acute diabetes emergency involving profound insulin deficiency, extreme hyperglycemia, acidosis, or severe dehydration.',
        'meaning_km': 'ស្ថានភាពគ្រោះថ្នាក់ដល់អាយុជីវិតដោយសារកង្វះអាំងស៊ុយលីនធ្ងន់ធ្ងរ ជាតិស្ករឡើងខ្ពស់ខ្លាំង អាស៊ីតក្នុងឈាមកើនឡើង ឬខ្វះជាតិទឹកកម្រិតធ្ងន់។',
        'prevention': 'Requires immediate emergency hospital admission for IV fluids, intravenous insulin, and electrolyte correction. Never stop prescribed insulin during illness.',
        'prevention_km': 'តម្រូវឱ្យបញ្ជូនទៅសង្គ្រោះបន្ទាន់នៅមន្ទីរពេទ្យភ្លាមៗដើម្បីចាក់បញ្ចូលសេរ៉ូម អាំងស៊ុយលីន និងកែតម្រូវជាតិអេឡិចត្រូលីត។ កុំបញ្ឈប់ការចាក់អាំងស៊ុយលីនពេលឈឺ។',
        'weight': 0.35,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': True,
        'aliases': ['metabolic_crisis'],
        'display_order': 200,
    },
    {
        'key': 'fruity_breath',
        'label': 'Fruity-Smelling Breath',
        'label_km': 'ដង្ហើមមានក្លិនផ្លែឈើ',
        'medical_term': 'Ketone breath (Acetone breath)',
        'category': 'emergency',
        'question': 'Have others noticed a fruity, acetone, or nail-polish smell to your breath?',
        'question_km': 'តើអ្នកដទៃធ្លាប់កត់សម្គាល់ឃើញខ្យល់ដង្ហើមរបស់អ្នកមានក្លិនផ្អែម ក្លិនផ្លែឈើ ឬក្លិនថ្នាំលាងក្រចក (អាសេតូន) ដែរឬទេ?',
        'meaning': 'Possible diabetic ketoacidosis (DKA) — seek care urgently.',
        'meaning_km': 'អាចជា DKA (ketone ខ្ពស់) — ត្រូវទៅពេទ្យបន្ទាន់។',
        'prevention': 'This can signal DKA (a dangerous chemical imbalance) — check ketones and seek urgent care.',
        'prevention_km': 'នេះអាចជាសញ្ញា DKA (ភាពមិនតុល្យភាពគីមីដ៏អាចម៍ផ្សែ) — ពិនិត្យ ketones និងស្វែងរកការព្យាបាលសង្គ្រោះបន្ទាន់។',
        'weight': 0.25,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'aliases': ['ketone_breath'],
        'display_order': 210,
    },
    {
        'key': 'nausea',
        'label': 'Nausea',
        'label_km': 'ចង់ក្អួត',
        'medical_term': 'Nausea',
        'category': 'emergency',
        'question': 'Do you feel nauseous or sick to your stomach?',
        'question_km': 'តើអ្នកមានអារម្មណ៍ចង់ក្អួត ឬចង្អោរមិនស្រួលក្នុងពោះឬ?',
        'meaning': 'Can occur when blood glucose or ketones are very high.',
        'meaning_km': 'អាចកើតពេលជាតិស្ករឬ ketone ខ្ពស់ខ្លាំង។',
        'prevention': 'Sip water slowly and seek care if it persists — nausea with high sugar can be serious.',
        'prevention_km': 'ពឹងទឹកបន្តិចម្តងៗ និងទៅពិនិត្យប្រសិនបើវាបន្ត — ក្អួតចង្អោរជាមួយជាតិស្ករខ្ពស់អាចមានគ្រោះថ្នាក់។',
        'weight': 0.1,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 220,
    },
    {
        'key': 'rapid_breathing',
        'label': 'Rapid or Deep Breathing',
        'label_km': 'ដង្ហើមញាប់ ឬដង្ហើមជ្រៅ',
        'medical_term': 'Kussmaul respiration',
        'category': 'emergency',
        'question': 'Is breathing unusually fast, deep, or labored without physical exertion?',
        'question_km': 'តើការដកដង្ហើមរបស់អ្នកលឿន ជ្រៅ ឬពិបាកដកដង្ហើមខុសធម្មតាដោយមិនបានធ្វើការធ្ងន់ឬ?',
        'meaning': "The body's respiratory compensatory mechanism to blow off volatile acidic carbon dioxide in response to diabetic ketoacidosis (DKA).",
        'meaning_km': 'យន្តការដកដង្ហើមរបស់រាងកាយដើម្បីបញ្ចេញឧស្ម័នកាបូនិចអាស៊ីតចេញក្រៅ ដើម្បីឆ្លើយតបទៅនឹងស្ថានភាពអាស៊ីតកើនឡើង (DKA)។',
        'prevention': 'Check blood glucose and ketones immediately. If elevated, seek emergency medical care without delay.',
        'prevention_km': 'ពិនិត្យជាតិស្ករក្នុងឈាម និងកម្រិត ketone ភ្លាមៗ។ ប្រសិនបើឡើងខ្ពស់ ត្រូវទៅសង្គ្រោះបន្ទាន់ភ្លាមៗ។',
        'weight': 0.15,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 230,
    },
    {
        'key': 'unable_to_keep_fluids',
        'label': 'Unable to Keep Fluids Down',
        'label_km': 'មិនអាចរក្សាជាតិទឹកក្នុងពោះបាន (ក្អួតរាល់ពេលផឹក)',
        'medical_term': 'Intractable vomiting',
        'category': 'emergency',
        'question': 'Are you vomiting everything you drink and unable to stay hydrated for more than 4-6 hours?',
        'question_km': 'តើអ្នកក្អួតរាល់ពេលញ៉ាំទឹក និងមិនអាចរក្សាជាតិទឹកក្នុងខ្លួនលើសពី ៤-៦ ម៉ោងឬ?',
        'meaning': 'Inability to retain liquids rapidly causes severe hypovolemia, kidney strain, and precipitates diabetic ketoacidosis in diabetic patients.',
        'meaning_km': 'ការមិនអាចទទួលទានទឹកបានបណ្តាលឱ្យខ្វះជាតិទឹកធ្ងន់ធ្ងរ ប៉ះពាល់តម្រងនោម និងជំរុញឱ្យកើតវិបត្តិ DKA យ៉ាងឆាប់រហ័ស។',
        'prevention': 'Take tiny sips of electrolyte solution every 5 minutes. If vomiting persists beyond a few hours with high glucose, go to the emergency room for IV rehydration.',
        'prevention_km': 'ក្រេបទឹកអេឡិចត្រូលីតបន្តិចម្តងៗរៀងរាល់ ៥ នាទី។ ប្រសិនបើនៅតែក្អួតលើសពី ២-៣ ម៉ោង ត្រូវទៅបន្ទប់សង្គ្រោះបន្ទាន់ដើម្បីបញ្ចូលជាតិទឹកតាមសរសៃ។',
        'weight': 0.2,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 240,
    },
    {
        'key': 'vomiting',
        'label': 'Vomiting',
        'label_km': 'ក្អួត',
        'medical_term': 'Emesis',
        'category': 'emergency',
        'question': 'Have you been vomiting or throwing up?',
        'question_km': 'តើអ្នកធ្លាប់ក្អួតចង្អោរ ឬក្អួតញឹកញាប់ដែរឬទេ?',
        'meaning': 'With very high glucose this can signal DKA — seek care urgently.',
        'meaning_km': 'ពេលជាតិស្ករខ្ពស់ខ្លាំងអាចជាសញ្ញា DKA — ទៅពេទ្យបន្ទាន់។',
        'prevention': 'Seek medical care quickly — vomiting with high glucose risks dehydration and DKA.',
        'prevention_km': 'ទៅរកការព្យាបាលវេជ្ជសាស្ត្រឱ្យលឿន — ការក្អួតជាមួយជាតិស្ករខ្ពស់មានហានិភ័យភាពស្រកទឹក និង DKA។',
        'weight': 0.15,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 250,
    },
    {
        'key': 'bed_wetting',
        'label': 'Bed-Wetting in Children',
        'label_km': 'ស្រោចលើគ្រែ (កុមារ)',
        'medical_term': 'Secondary nocturnal enuresis',
        'category': 'pediatric',
        'question': 'Has bed-wetting started in a child who was previously dry at night?',
        'question_km': 'តើកុមារដែលធ្លាប់ឈប់នោមដាក់កន្ទេល ចាប់ផ្តើមនោមដាក់កន្ទេលឡើងវិញនៅពេលយប់ឬ?',
        'meaning': 'Extra glucose pulls more water — a classic Type 1 sign in children.',
        'meaning_km': 'ជាតិស្ករលើសទាញទឹកច្រើន — សញ្ញាសំខាន់នៃប្រភេទទី 1 ក្នុងកុមារ។',
        'prevention': 'A quick glucose check today can rule out early diabetes — see a doctor promptly.',
        'prevention_km': 'ធ្វើតេស្តជាតិស្ករឆាប់រហ័សថ្ងៃនេះ អាចច្បាស់កាត់ជំងឺទឹកនោមផ្អែមដំណាក់កាលដំបូង — ទៅជួបវេជ្ជបណ្ឌិតឱ្យឆាប់។',
        'weight': 0.18,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['nocturnal_enuresis'],
        'display_order': 260,
    },
    {
        'key': 'diaper_rash',
        'label': 'Persistent Diaper Rash',
        'label_km': 'រលាកកន្ទួលក្រណាត់កន្ទបជាប់រហូត (កុមារ)',
        'medical_term': 'Candidal diaper dermatitis',
        'category': 'pediatric',
        'question': 'Does your child have a bright red diaper rash that fails to improve with usual diaper creams?',
        'question_km': 'តើកូនរបស់អ្នកមានកន្ទួលក្រហមខ្លាំងនៅតំបន់កន្ទប ដែលមិនធូរស្រាលទោះបីប្រើក្រែមលាបធម្មតាឬ?',
        'meaning': 'High urinary glucose excretion in babies with undiagnosed Type 1 diabetes fuels aggressive Candida fungal infections in the diaper zone.',
        'meaning_km': 'ជាតិស្ករលើសនៅក្នុងទឹកនោមរបស់កុមារដែលមានជំងឺទឹកនោមផ្អែមប្រភេទទី ១ ដែលមិនទាន់ដឹង ជំរុញឱ្យផ្សិត Candida រីករាលដាលខ្លាំងនៅលើកន្ទប។',
        'prevention': 'Consult a pediatrician promptly for a simple blood glucose screening test whenever a diaper rash is unusually severe, spreading, or recurrent.',
        'prevention_km': 'ទៅពិគ្រោះជាមួយគ្រូពេទ្យកុមារជាបន្ទាន់ដើម្បីធ្វើតេស្តជាតិស្ករក្នុងឈាមសាមញ្ញ ពេលដែលកន្ទួលកន្ទបមានសភាពធ្ងន់ធ្ងរ ឬព្យាបាលមិនជា។',
        'weight': 0.1,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 270,
    },
    {
        'key': 'deep_rapid_breathing',
        'label': 'Deep Rapid Breathing (Kussmaul)',
        'label_km': 'ដង្ហើមធំលឿន (Kussmaul)',
        'medical_term': 'Kussmaul breathing',
        'category': 'emergency',
        'question': 'Are you breathing deeply and rapidly as if gasping for air even while resting?',
        'question_km': 'តើអ្នកដកដង្ហើមជ្រៅៗ និងញាប់ៗដូចជាខ្វះខ្យល់ដង្ហើម ទោះបីជាកំពុងសម្រាកក៏ដោយឬ?',
        'meaning': 'The body tries to release ketone acids — seek care urgently.',
        'meaning_km': 'រាងកាយប្រឹងប្រែងបញ្ចេញអាស៊ីត ketone — ត្រូវទៅពេទ្យបន្ទាន់។',
        'prevention': 'An emergency sign (possible DKA) — go to emergency care immediately.',
        'prevention_km': 'សញ្ញាសង្គ្រោះបន្ទាន់ (អាចជា DKA) — ទៅព្យាបាលសង្គ្រោះបន្ទាន់ភ្លាមៗ។',
        'weight': 0.2,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'aliases': ['kussmaul_breathing'],
        'display_order': 280,
    },
    {
        'key': 'dizziness',
        'label': 'Dizziness',
        'label_km': 'វិលមុខ',
        'medical_term': 'Presyncope / Lightheadedness',
        'category': 'other',
        'question': 'Do you feel lightheaded, faint, or dizzy when standing up or sitting down?',
        'question_km': 'តើអ្នកមានអារម្មណ៍ស្រាលក្បាល ចង់សន្លប់ ឬវិលមុខនៅពេលក្រោកឈរ ឬអង្គុយឬ?',
        'meaning': 'Can come from low — or very high — blood sugar.',
        'meaning_km': 'អាចមកពីជាតិស្ករទាប — ឬខ្ពស់ខ្លាំង។',
        'prevention': 'Sit down and check glucose; treat lows quickly and seek help if it is severe.',
        'prevention_km': 'អង្គុយចុះ និងពិនិត្យជាតិស្ករ។ ព្យាបាលជាតិស្ករទាបឱ្យលឿន និងទៅរកជំនួយប្រសិនបើធ្ងន់ធ្ងរ។',
        'weight': 0.08,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 290,
    },
    {
        'key': 'recurrent_uti_yeast',
        'label': 'Recurrent UTI / Yeast Infections',
        'label_km': 'ឆ្លងរោគផ្លូវទឹកនោម ឬផ្សិតញឹកញាប់',
        'medical_term': 'Recurrent genitourinary infections',
        'category': 'other',
        'question': 'Do you experience frequent urinary tract infections (painful urination) or yeast infections?',
        'question_km': 'តើអ្នកឧស្សាហ៍ឆ្លងរោគផ្លូវទឹកនោម (នោមផ្សា/នោមឈឺ) ឬកើតរោគផ្សិតញឹកញាប់ឬ?',
        'meaning': 'Glucose in urine feeds bacteria and yeast.',
        'meaning_km': 'ជាតិស្ករក្នុងនោមធ្វើឱ្យបាកតេរី និងផ្សិតលូតលាស់។',
        'prevention': 'Control sugar levels, stay hydrated, and see a doctor for infections that keep coming back.',
        'prevention_km': 'គ្រប់គ្រងកម្រិតជាតិស្ករ ផឹកទឹកឱ្យបានគ្រប់គ្រាន់ និងទៅជួបវេជ្ជបណ្ឌិតពេលមានការឆ្លងមេរោគដដែលៗ។',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['recurrent_infections_uti_yeast'],
        'display_order': 300,
    },
    {
        'key': 'shaking',
        'label': 'Shaking / Tremors',
        'label_km': 'ញ័រដៃជើង',
        'medical_term': 'Tremor / Autonomic hyperactivity',
        'category': 'other',
        'question': 'Do your hands or body tremble and shake without being cold?',
        'question_km': 'តើដៃ ឬរាងកាយរបស់អ្នកញ័រ ឬកន្ត្រាក់ដោយមិនមែនមកពីរងាឬ?',
        'meaning': 'Common warning sign of low blood sugar (hypoglycemia).',
        'meaning_km': 'សញ្ញាទូទៅនៃជាតិស្ករទាប (hypoglycemia)។',
        'prevention': 'Test glucose now — trembling often means low sugar; use the 15/15 rule if below 70 mg/dL.',
        'prevention_km': 'ពិនិត្យជាតិស្ករភ្លាម — ការញ័រភាគច្រើនមានន័យថាជាតិស្ករទាប។ ប្រើក្បួន ១៥/១៥ ប្រសិនបើក្រោម ៧០ mg/dL។',
        'weight': 0.1,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 310,
    },
    {
        'key': 'sweating',
        'label': 'Cold Sweats / Profuse Sweating',
        'label_km': 'បែកញើសខ្លាំង / ញើសត្រជាក់',
        'medical_term': 'Diaphoresis',
        'category': 'other',
        'question': 'Do you break out in sudden cold sweats or perspire heavily even in cool conditions?',
        'question_km': 'តើអ្នកបែកញើសត្រជាក់ភ្លាមៗ ឬបែកញើសខ្លាំងទោះបីនៅក្នុងកន្លែងត្រជាក់ក៏ដោយឬ?',
        'meaning': 'Can be a warning sign of low blood sugar (hypoglycemia).',
        'meaning_km': 'អាចជាសញ្ញាជាតិស្ករទាប (hypoglycemia)។',
        'prevention': 'Check blood sugar — sweating can signal a low; keep fast-acting sugar within reach.',
        'prevention_km': 'ពិនិត្យជាតិស្ករក្នុងឈាម — ញៀរញាប់អាចជាសញ្ញាជាតិស្ករទាប។ កាន់ស្កររលត់លឿននៅជាប់ខ្លួនជានិច្ច។',
        'weight': 0.1,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 320,
    },
    {
        'key': 'ethnicity_high_risk',
        'label': 'High-Risk Ethnicity',
        'label_km': 'ជាតិសាសន៍ដែលមានហានិភ័យខ្ពស់',
        'medical_term': 'High-risk racial/ethnic predisposition',
        'category': 'risk_factor',
        'question': 'Do you belong to an ethnic population known to have higher diabetes risk at lower BMI (e.g. South/Southeast Asian)?',
        'question_km': 'តើអ្នកជាជនជាតិអាស៊ី (អាស៊ីខាងត្បូង ឬអាស៊ីអាគ្នេយ៍) ដែលមានហានិភ័យទឹកនោមផ្អែមខ្ពស់ទោះបីកម្រិត BMI ទាបឬ?',
        'meaning': 'Some ethnic groups (South Asian, Southeast Asian and others) face higher risk at lower weights — screen earlier.',
        'meaning_km': 'ជនជាតិខ្លះ (អាស៊ីខាងត្បូង អាស៊ីអាគ្នេយ៍ ជាដើម) មានហានិភ័យខ្ពស់ជាង ទោះទម្ងន់ធម្មតា — គួរពិនិត្យទាន់ពេលជាង។',
        'prevention': 'Begin annual diabetes screening from age 35 (or earlier if BMI ≥23 for Asian populations) and maintain a healthy plant-rich diet.',
        'prevention_km': 'ចាប់ផ្តើមពិនិត្យជាតិស្ករប្រចាំឆ្នាំចាប់ពីអាយុ ៣៥ ឆ្នាំ (ឬលឿនជាងនេះបើ BMI ≥23 សម្រាប់ជនជាតិអាស៊ី) និងទទួលទានអាហារបន្លែផ្លែឈើឱ្យបានច្រើន។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 330,
    },
    {
        'key': 'family_history',
        'label': 'Family History of Diabetes',
        'label_km': 'ប្រវត្តិគ្រួសារមានទឹកនោមផ្អែម',
        'medical_term': 'First-degree family history of diabetes mellitus',
        'category': 'risk_factor',
        'question': 'Has any immediate family member (parent, sibling, or child) been diagnosed with diabetes?',
        'question_km': 'តើសមាជិកគ្រួសារផ្ទាល់របស់អ្នក (ឪពុកម្តាយ បងប្អូនបង្កើត ឬកូន) ធ្លាប់មានជំងឺទឹកនោមផ្អែមដែរឬទេ?',
        'meaning': 'A parent or sibling with diabetes raises your lifetime risk — screening should start earlier and repeat regularly.',
        'meaning_km': 'បើមានឪពុកម្តាយ ឬបងប្អូនជំងឺទឹកនោមផ្អែម ហានិភ័យរបស់អ្នកកើនឡើង — គួរពិនិត្យទាន់ពេល និងធ្វើជាប្រចាំ។',
        'prevention': 'Engage in 150 minutes of weekly moderate aerobic activity, maintain ideal body weight, and screen fasting glucose annually.',
        'prevention_km': 'ធ្វើលំហាត់ប្រាណកម្រិតមធ្យម ១៥០ នាទីក្នុងមួយសប្តាហ៍ រក្សាទម្ងន់ឱ្យសមស្រប និងពិនិត្យជាតិស្ករពេលតមអាហារជារៀងរាល់ឆ្នាំ។',
        'weight': 0.1,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['family_history_diabetes'],
        'display_order': 340,
    },
    {
        'key': 'gestational_history',
        'label': 'Prior Gestational Diabetes',
        'label_km': 'ប្រវត្តិទឹកនោមផ្អែមពេលមានផ្ទៃពោះ',
        'medical_term': 'History of gestational diabetes mellitus (GDM)',
        'category': 'risk_factor',
        'question': 'Did you develop high blood sugar or gestational diabetes during any past pregnancy?',
        'question_km': 'តើអ្នកធ្លាប់មានជាតិស្ករឡើងខ្ពស់ ឬកើតជំងឺទឹកនោមផ្អែមពេលមានផ្ទៃពោះពីមុនមកឬ?',
        'meaning': 'Diabetes during pregnancy means a high chance of type 2 later in life — test every 1–3 years.',
        'meaning_km': 'ទឹកនោមផ្អែមពេលមានផ្ទៃពោះ មានឱកាសខ្ពស់ក្លាយជាប្រភេទទី ២ ពេលអនាគត — គួរពិនិត្យរាល់ ១–៣ ឆ្នាំ។',
        'prevention': 'Undergo an OGTT or HbA1c test 4–12 weeks postpartum, followed by lifelong diabetes screening every 1 to 3 years.',
        'prevention_km': 'ធ្វើតេស្ត OGTT ឬ HbA1c នៅសប្តាហ៍ទី ៤-១២ ក្រោយសម្រាល និងបន្តពិនិត្យរកទឹកនោមផ្អែមរៀងរាល់ ១ ទៅ ៣ ឆ្នាំពេញមួយជីវិត។',
        'weight': 0.1,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 350,
    },
    {
        'key': 'high_cholesterol',
        'label': 'High Cholesterol',
        'label_km': 'ជាតិខ្លាញ់កូឡេស្តេរ៉ុលខ្ពស់',
        'medical_term': 'Dyslipidemia / Hypercholesterolemia',
        'category': 'risk_factor',
        'question': 'Have you been diagnosed with high cholesterol, elevated LDL, high triglycerides, or low HDL?',
        'question_km': 'តើអ្នកធ្លាប់ត្រូវបានរកឃើញថាមានជាតិខ្លាញ់ក្នុងឈាមខ្ពស់ (កូឡេស្តេរ៉ុលខ្ពស់, ទ្រីគ្លីសេរីដខ្ពស់ ឬ HDL ទាប) ដែរឬទេ?',
        'meaning': 'High cholesterol together with high sugar speeds up artery damage — diet, movement and medication help.',
        'meaning_km': 'ជាតិប្រេងខ្ពស់ទៅជាមួយជាតិស្ករខ្ពស់ ធ្វើឱ្យសរសៃឈាមខូចលឿនជាង — អាហារូបត្ថម្ភ ការហាត់ប្រាណ និងថ្នាំជួយបាន។',
        'prevention': 'Adopt a Mediterranean or DASH diet low in saturated and trans fats, exercise regularly, and take lipid-lowering medication as prescribed.',
        'prevention_km': 'ទទួលទានអាហារបែបមេឌីទែរ៉ាណេ ឬ DASH ដែលមានជាតិខ្លាញ់ឆ្អែតទាប ហាត់ប្រាណទៀងទាត់ និងលេបថ្នាំបញ្ចុះជាតិខ្លាញ់តាមវេជ្ជបញ្ជា។',
        'weight': 0.08,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 360,
    },
    {
        'key': 'hypertension',
        'label': 'High Blood Pressure',
        'label_km': 'សម្ពាធឈាមខ្ពស់',
        'medical_term': 'Essential hypertension',
        'category': 'risk_factor',
        'question': 'Have you been diagnosed with high blood pressure (≥130/80 mmHg) or are you taking antihypertensive medication?',
        'question_km': 'តើអ្នកធ្លាប់ត្រូវបានរកឃើញថាមានជំងឺលើសឈាម (≥១៣០/៨០ mmHg) ឬកំពុងលេបថ្នាំបញ្ចុះសម្ពាធឈាមឬ?',
        'meaning': 'High blood pressure often travels with high sugar and doubles the risk to the heart and kidneys.',
        'meaning_km': 'សម្ពាធឈាមខ្ពស់ជារឿយៗមកជាមួយជាតិស្ករខ្ពស់ និងបង្កើនហានិភ័យដល់បេះដូង និងតម្រងនោមទ្វេដង។',
        'prevention': 'Reduce sodium intake (<2,300 mg/day), exercise at least 30 minutes daily, limit alcohol, and keep blood pressure below 130/80 mmHg.',
        'prevention_km': 'កាត់បន្ថយការញ៉ាំប្រៃ (<២៣០០ មីលីក្រាម/ថ្ងៃ) ហាត់ប្រាណយ៉ាងតិច ៣០ នាទីរាល់ថ្ងៃ កម្រិតគ្រឿងស្រវឹង និងរក្សាសម្ពាធឈាមក្រោម ១៣០/៨០ mmHg។',
        'weight': 0.08,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 370,
    },
    {
        'key': 'obesity',
        'label': 'Obesity',
        'label_km': 'ជំងឺធាត់ / លើសទម្ងន់ខ្លាំង',
        'medical_term': 'Obesity (BMI ≥ 30 kg/m²)',
        'category': 'risk_factor',
        'question': 'Is your Body Mass Index (BMI) 30 kg/m² or higher, or do you have significant excess abdominal fat?',
        'question_km': 'តើសន្ទស្សន៍ម៉ាសរាងកាយ (BMI) របស់អ្នកចាប់ពី ៣០ kg/m² ឡើងទៅ ឬមានខ្លាញ់ក្បាលពោះច្រើនលើសលប់ឬ?',
        'meaning': 'Excess body fat — especially around the waist — makes the body resistant to insulin, the top driver of type 2 diabetes.',
        'meaning_km': 'ខ្លាញ់លើសពិសេសនៅជុំវិញពោះ ធ្វើឱ្យរាងកាយធន់ទ្រាំនឹង insulin ដែលជាមូលហេតុចម្បងនៃជំងឺទឹកនោមផ្អែមប្រភេទទី ២។',
        'prevention': 'Target a sustainable 7–10% body weight reduction through caloric deficit, resistance training, and nutritional counseling.',
        'prevention_km': 'កំណត់គោលដៅកាត់បន្ថយទម្ងន់ ៧-១០% តាមរយៈការកាត់បន្ថយកាឡូរី ហាត់ប្រាណពង្រឹងសាច់ដុំ និងការប្រឹក្សាអាហារូបត្ថម្ភ។',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 380,
    },
    {
        'key': 'overweight',
        'label': 'Overweight (BMI 25-30)',
        'label_km': 'លើសទម្ងន់ (BMI ២៥–៣០)',
        'medical_term': 'Overweight (BMI 25.0–29.9 kg/m²)',
        'category': 'risk_factor',
        'question': 'Is your Body Mass Index (BMI) between 25 and 29.9 kg/m² (or ≥23 kg/m² for Asian populations)?',
        'question_km': 'តើសន្ទស្សន៍ម៉ាសរាងកាយ (BMI) របស់អ្នកស្ថិតនៅចន្លោះ ២៣ ទៅ ២៧.៤ kg/m² (កម្រិតលើសទម្ងន់សម្រាប់ជនជាតិអាស៊ី) ឬ?',
        'meaning': 'A BMI of 25–30 already raises type 2 risk; a modest 5–10% weight loss brings it down sharply.',
        'meaning_km': 'BMI ចន្លោះ ២៥–៣០ បង្កើនហានិភ័យប្រភេទទី ២ រួចទៅហើយ។ បន្ថយទម្ងន់ ៥–១០% អាចកាត់បន្ថយវាយ៉ាងខ្លាំង។',
        'prevention': 'A modest 5% weight loss combined with 150 minutes of weekly brisk walking dramatically lowers progression to Type 2 diabetes.',
        'prevention_km': 'ការបញ្ចុះទម្ងន់ត្រឹមតែ ៥% រួមផ្សំជាមួយការដើរលឿន ១៥០ នាទីក្នុងមួយសប្តាហ៍ ជួយកាត់បន្ថយការវិវឌ្ឍន៍ទៅជាទឹកនោមផ្អែមប្រភេទទី ២ បានយ៉ាងច្រើន។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 390,
    },
    {
        'key': 'pcos_history',
        'label': 'PCOS History',
        'label_km': 'ប្រវត្តិជំងឺគីសទឹកក្រពេញអូវែ (PCOS)',
        'medical_term': 'Polycystic ovary syndrome (PCOS)',
        'category': 'risk_factor',
        'question': 'Have you been diagnosed with Polycystic Ovary Syndrome (PCOS) or chronic menstrual irregularities with hirsutism?',
        'question_km': 'តើអ្នកធ្លាប់ត្រូវបានធ្វើរោគវិនិច្ឆ័យឃើញរោគសញ្ញាគីសទឹកក្រពេញអូវែ (PCOS) ឬមានរដូវមិនទៀងទាត់រ៉ាំរ៉ៃឬ?',
        'meaning': 'PCOS is strongly linked to insulin resistance — women with PCOS need regular glucose checks.',
        'meaning_km': 'PCOS ទាក់ទងយ៉ាងខ្លាំងនឹងភាពធន់ទ្រាំ insulin — ស្ត្រីដែលមាន PCOS គួរពិនិត្យជាតិស្ករជាប្រចាំ។',
        'prevention': 'Screen fasting glucose and HbA1c annually, maintain an active lifestyle, and discuss insulin-sensitizing therapy with your doctor.',
        'prevention_km': 'ពិនិត្យជាតិស្ករពេលតមអាហារ និង HbA1c រៀងរាល់ឆ្នាំ រស់នៅបែបសកម្ម និងពិភាក្សាជាមួយគ្រូពេទ្យអំពីវិធីបង្កើនភាពប្រែប្រួលអាំងស៊ុយលីន។',
        'weight': 0.08,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 400,
    },
    {
        'key': 'sedentary_lifestyle',
        'label': 'Sedentary Lifestyle',
        'label_km': 'ការរស់នៅមិនសូវមានសកម្មភាពរាងកាយ',
        'medical_term': 'Sedentary behavior / Physical inactivity',
        'category': 'risk_factor',
        'question': 'Do you sit for most of the day with very little physical exercise (less than 30 minutes a week)?',
        'question_km': 'តើអ្នកអង្គុយច្រើនម៉ោងក្នុងមួយថ្ងៃ ដោយកម្របានហាត់ប្រាណ (តិចជាង ៣០ នាទីក្នុងមួយសប្តាហ៍) ឬ?',
        'meaning': 'Sitting most of the day weakens glucose control — 150 minutes of movement a week cuts risk by about a third.',
        'meaning_km': 'អង្គុយភាគច្រើនក្នុងមួយថ្ងៃ ធ្វើឱ្យការគ្រប់គ្រងជាតិស្ករអន់ជាង។ ហាត់ប្រាណ ១៥០ នាទីក្នុងមួយសប្តាហ៍ អាចកាត់បន្ថយហានិភ័យប្រហែលមួយភាគបី។',
        'prevention': 'Break up long sitting periods every 30 minutes with 2 minutes of walking, and build up to 150 minutes of moderate activity weekly.',
        'prevention_km': 'ក្រោកដើរ ២ នាទីរៀងរាល់ការអង្គុយ ៣០ នាទី និងបង្កើនសកម្មភាពរាងកាយកម្រិតមធ្យមឱ្យបាន ១៥០ នាទីក្នុងមួយសប្តាហ៍។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['physical_activity_low'],
        'display_order': 410,
    },
    {
        'key': 'smoking',
        'label': 'Smoking',
        'label_km': 'ការជក់បារី',
        'medical_term': 'Tobacco use disorder',
        'category': 'risk_factor',
        'question': 'Do you currently smoke cigarettes or use tobacco products regularly?',
        'question_km': 'តើបច្ចុប្បន្នអ្នកជក់បារី ឬប្រើប្រាស់ថ្នាំជក់ជាប្រចាំដែរឬទេ?',
        'meaning': 'Smoking worsens insulin resistance and damages blood vessels — quitting is the single best step.',
        'meaning_km': 'ជក់បារីធ្វើឱ្យភាពធន់ទ្រាំ insulin ធ្ងន់ធ្ងរ និងខូចសរសៃឈាម — ការលះបង់ជក់បារីជាជំហានល្អបំផុត។',
        'prevention': 'Enroll in a smoking cessation program and utilize nicotine replacement therapy if needed; quitting immediately improves insulin sensitivity.',
        'prevention_km': 'ចូលរួមកម្មវិធីផ្តាច់បារី និងប្រើប្រាស់ផលិតផលជំនួសជាតិនីកូទីនបើចាំបាច់ ការឈប់ជក់បារីជួយបង្កើនភាពប្រែប្រួលអាំងស៊ុយលីនភ្លាមៗ។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 420,
    },
    {
        'key': '2h_ogtt_75g',
        'label': '2-Hour Oral Glucose Tolerance Test (75 g)',
        'label_km': 'តេស្តជាតិស្ករ OGTT ២ ម៉ោង (៧៥ ក្រាម)',
        'medical_term': '75g Oral glucose tolerance test (2h-PG)',
        'category': 'lab',
        'question': 'What was your 2-hour plasma glucose value after drinking the 75g glucose liquid?',
        'question_km': 'តើតម្លៃជាតិស្ករក្នុងឈាម ២ ម៉ោងបន្ទាប់ពីពិសាទឹកស្ករ ៧៥ ក្រាម (តេស្ត OGTT) របស់អ្នកមានកម្រិតប៉ុន្មាន (mg/dL)?',
        'meaning': 'Blood glucose 2 hours after a 75 g glucose drink. Normal <140 mg/dL, prediabetes 140-199 mg/dL, diabetes >=200 mg/dL (ADA).',
        'meaning_km': 'វាស់ស្ទង់ជាតិស្ករក្នុងឈាម ២ ម៉ោងក្រោយផឹកទឹកជាតិស្ករ ៧៥ ក្រាម។ ធម្មតា <១៤០ mg/dL, មុនទឹកនោមផ្អែម ១៤០–១៩៩ mg/dL, ទឹកនោមផ្អែម ≥២០០ mg/dL (ADA)។',
        'prevention': 'Fast for 8–10 hours before testing. If elevated, begin medical nutrition therapy and retest annually.',
        'prevention_km': 'តមអាហារ ៨-១០ ម៉ោងមុនធ្វើតេស្ត។ ប្រសិនបើឡើងខ្ពស់ ត្រូវកែប្រែរបបអាហារ និងហាត់ប្រាណភ្លាមៗ ហើយធ្វើតេស្តឡើងវិញជារៀងរាល់ឆ្នាំ។',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['two_hour_ogtt_75g', 'ogtt_2h'],
        'display_order': 430,
    },
    {
        'key': 'fasting_glucose',
        'label': 'Fasting Plasma Glucose (FPG)',
        'label_km': 'ជាតិស្ករក្នុងឈាមពេលតមអាហារ (FPG)',
        'medical_term': 'Fasting plasma glucose (FPG)',
        'category': 'lab',
        'question': 'What was your fasting blood sugar reading after at least 8 hours of fasting?',
        'question_km': 'តើតម្លៃជាតិស្ករក្នុងឈាមពេលព្រឹកព្រលឹម (អត់អាហារយ៉ាងតិច ៨ ម៉ោង) របស់អ្នកមានកម្រិតប៉ុន្មាន (mg/dL)?',
        'meaning': 'Glucose after at least 8 hours without food. Normal <100 mg/dL, prediabetes 100-125 mg/dL, diabetes >=126 mg/dL (ADA).',
        'meaning_km': 'កម្រិតជាតិស្ករក្នុងឈាមបន្ទាប់ពីតមអាហារយ៉ាងតិច ៨ ម៉ោង។ ធម្មតា <១០០ mg/dL, មុនទឹកនោមផ្អែម ១០០–១២៥ mg/dL, ទឹកនោមផ្អែម ≥១២៦ mg/dL (ADA)។',
        'prevention': 'Get tested once a year if at risk; prevent progression by eating whole grains, cutting sugary drinks, and keeping an active routine.',
        'prevention_km': 'ធ្វើតេស្តម្តងក្នុងមួយឆ្នាំប្រសិនបើមានហានិភ័យ ការពារកុំឱ្យវិវឌ្ឍន៍ដោយទទួលទានគ្រាប់ធញ្ញជាតិ កាត់បន្ថយភេសជ្ជៈផ្អែម និងធ្វើលំហាត់ប្រាណជាប្រចាំ។',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['fasting_plasma_glucose'],
        'display_order': 440,
    },
    {
        'key': 'hba1c',
        'label': 'Glycated Hemoglobin (HbA1c)',
        'label_km': 'កម្រិតជាតិស្ករមធ្យម ៣ ខែ (HbA1c)',
        'medical_term': 'Glycated hemoglobin A1c',
        'category': 'lab',
        'question': 'What was your HbA1c percentage result from the laboratory test?',
        'question_km': 'តើលទ្ធផលភាគរយជាតិស្ករមធ្យម HbA1c របស់អ្នកទទួលបានប៉ុន្មាន (%)?',
        'meaning': 'Average blood glucose over about 3 months. Normal <5.7%, prediabetes 5.7-6.4%, diabetes >=6.5% (ADA).',
        'meaning_km': 'ឆ្លុះបញ្ចាំងពីកម្រិតជាតិស្ករមធ្យមក្នុងឈាមក្នុងអំឡុងពេល ២ ទៅ ៣ ខែចុងក្រោយ។ ធម្មតា <៥.៧%, មុនទឹកនោមផ្អែម ៥.៧–៦.៤%, ទឹកនោមផ្អែម ≥៦.៥% (ADA)។',
        'prevention': 'Target an HbA1c below 5.7% for prevention or below 7.0% for most adults with diabetes through lifestyle and tailored medication.',
        'prevention_km': 'កំណត់គោលដៅ HbA1c ឱ្យនៅក្រោម ៥.៧% សម្រាប់ការការពារ ឬក្រោម ៧.០% សម្រាប់អ្នកជំងឺទឹកនោមផ្អែម តាមរយៈរបៀបរស់នៅ និងថ្នាំត្រឹមត្រូវ។',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['a1c'],
        'display_order': 450,
    },
    {
        'key': 'random_plasma_glucose',
        'label': 'Random Plasma Glucose',
        'label_km': 'ជាតិស្ករក្នុងឈាមចៃដន្យ',
        'medical_term': 'Random / Casual plasma glucose',
        'category': 'lab',
        'question': 'What was your blood glucose reading taken at any random time of day?',
        'question_km': 'តើតម្លៃជាតិស្ករក្នុងឈាមដែលបានវាស់នៅពេលចៃដន្យរបស់អ្នកមានកម្រិតប៉ុន្មាន (mg/dL)?',
        'meaning': 'Glucose at any time of day. >=200 mg/dL together with classic symptoms suggests diabetes (ADA).',
        'meaning_km': 'កម្រិតជាតិស្ករដែលវាស់នៅពេលណាក៏បានដោយមិនគិតពីពេលវេលាញ៉ាំបាយ។ តម្លៃ ≥២០០ mg/dL រួមជាមួយរោគសញ្ញាសំខាន់ៗ បញ្ជាក់ថាមានជំងឺទឹកនោមផ្អែម (ADA)។',
        'prevention': 'Avoid bingeing on refined sugars prior to testing; follow up an abnormal reading with fasting glucose or an HbA1c test.',
        'prevention_km': 'ជៀសវាងញ៉ាំជាតិស្ករកែច្នៃច្រើនមុនពេលធ្វើតេស្ត បើលទ្ធផលមិនធម្មតា ត្រូវបន្តធ្វើតេស្តជាតិស្ករតមអាហារ ឬ HbA1c ដើម្បីបញ្ជាក់។',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['random_glucose'],
        'display_order': 460,
    },
    {
        'key': 'currently_pregnant',
        'label': 'Currently Pregnant',
        'label_km': 'កំពុងមានផ្ទៃពោះ',
        'medical_term': 'Pregnancy / Gestational status',
        'category': 'profile',
        'question': 'Are you currently pregnant?',
        'question_km': 'តើបច្ចុប្បន្នអ្នកកំពុងមានផ្ទៃពោះដែរឬទេ?',
        'meaning': 'Pregnancy uses stricter glucose thresholds (IADPSG / ADA criteria). Fasting >=92 mg/dL or 2h OGTT >=153 mg/dL indicates gestational diabetes.',
        'meaning_km': 'ពេលមានផ្ទៃពោះត្រូវប្រើកម្រិតជាតិស្ករម៉ត់ចត់ជាងធម្មតា (ស្តង់ដារ IADPSG/ADA)។ ជាតិស្ករតមអាហារ ≥៩២ mg/dL ឬ OGTT ២ម៉ោង ≥១៥៣ mg/dL បង្ហាញពីទឹកនោមផ្អែមពេលមានផ្ទៃពោះ។',
        'prevention': 'Screen for gestational diabetes at 24–28 weeks of pregnancy (or earlier if high-risk) and follow an obstetric nutrition plan.',
        'prevention_km': 'ពិនិត្យរកទឹកនោមផ្អែមពេលមានផ្ទៃពោះនៅសប្តាហ៍ទី ២៤-២៨ (ឬលឿនជាងនេះបើមានហានិភ័យ) និងអនុវត្តតាមរបបអាហារដែលគ្រូពេទ្យសម្ភពណែនាំ។',
        'weight': 0.0,
        'type_indication': 'gdm',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 470,
    },
    {
        'key': 'rapid_onset',
        'label': 'Rapid Symptom Onset',
        'label_km': 'រោគសញ្ញាលេចឡើងលឿន (ពីរបីថ្ងៃទៅសប្តាហ៍)',
        'medical_term': 'Acute symptomatic onset',
        'category': 'profile',
        'question': 'Did your symptoms appear rapidly over days to weeks rather than gradually over months?',
        'question_km': 'តើរោគសញ្ញារបស់អ្នកបានលេចឡើងយ៉ាងលឿនក្នុងរយៈពេលប៉ុន្មានថ្ងៃទៅសប្តាហ៍ ឬវិវត្តយឺតៗរាប់ខែ?',
        'meaning': 'Symptoms appearing suddenly over days to weeks fit the Type 1 diabetes insulin-deficiency tempo, whereas Type 2 develops slowly over years.',
        'meaning_km': 'រោគសញ្ញាលេចឡើងភ្លាមៗក្នុងរយៈពេលប៉ុន្មានថ្ងៃទៅសប្តាហ៍ ស្របនឹងល្បឿនខ្វះអាំងស៊ុយលីននៃប្រភេទទី ១ ខណៈប្រភេទទី ២ វិវឌ្ឍយឺតៗរាប់ឆ្នាំ។',
        'prevention': 'Seek urgent same-day medical review with fingerstick glucose and ketone testing to rule out diabetic ketoacidosis (DKA).',
        'prevention_km': 'ទៅជួបគ្រូពេទ្យក្នុងថ្ងៃតែមួយដើម្បីធ្វើតេស្តជាតិស្ករចាក់ម្រាមដៃ និងតេស្ត ketone ដើម្បីការពារវិបត្តិ DKA ដែលអាចគំរាមកំហែងដល់អាយុជីវិត។',
        'weight': 0.0,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 480,
    },
    {
        'key': 'burning_sensation',
        'label': 'Burning Sensation In Extremities',
        'label_km': 'អារម្មណ៍ក្តៅក្រហាយនៅចុងដៃចុងជើង',
        'medical_term': 'Diabetic paresthesia / Burning neuropathic pain',
        'category': 'neuropathy',
        'question': 'Do you feel burning sensations or abnormal heat in your hands, feet, or legs?',
        'question_km': 'តើអ្នកមានអារម្មណ៍ក្តៅក្រហាយនៅជើង ឬដៃដែរឬទេ?',
        'meaning': 'Elevated blood glucose damages small sensory nerve fibers, causing painful burning, stinging, or hypersensitivity in extremities.',
        'meaning_km': 'ជាតិស្ករក្នុងឈាមខ្ពស់បំផ្លាញសរសៃប្រសាទវិញ្ញាណតូចៗ បណ្តាលឱ្យមានអារម្មណ៍ក្តៅក្រហាយ ឈឺឆៀបៗ ឬរហ័សដឹងរំញោចខ្លាំងនៅចុងដៃចុងជើង។',
        'prevention': 'Maintain strict glucose control, wear protective cushioned footwear, inspect feet daily, and avoid walking barefoot.',
        'prevention_km': 'គ្រប់គ្រងជាតិស្ករឱ្យបានម៉ត់ចត់ ពាក់ស្បែកជើងការពារដែលមានទ្រនាប់ទន់ ពិនិត្យបាតជើងរាល់ថ្ងៃ និងជៀសវាងការដើរជើងទទេរ។',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 490,
    },
    {
        'key': 'numbness',
        'label': 'Numbness In Extremities',
        'label_km': 'ស្ពឹកស្រពន់នៅចុងដៃចុងជើង',
        'medical_term': 'Sensory hypoesthesia',
        'category': 'neuropathy',
        'question': 'Have you noticed numbness or loss of feeling in your toes, feet, or fingers?',
        'question_km': 'តើអ្នកមានអារម្មណ៍ស្ពឹក ឬបាត់បង់អារម្មណ៍នៅម្រាមជើង ឬជើងដែរឬទេ?',
        'meaning': 'Advanced peripheral neuropathy diminishes tactile and temperature sensation, putting feet at high risk of unnoticed injuries and ulcers.',
        'meaning_km': 'ជំងឺសរសៃប្រសាទគ្រឿងកម្រិតធ្ងន់ធ្វើឱ្យថយចុះការដឹងរំញោចប៉ះពាល់ និងកម្តៅ ដែលធ្វើឱ្យជើងប្រឈមនឹងការកើតរបួសដោយមិនដឹងខ្លួន។',
        'prevention': 'Perform daily foot inspections for cuts or blisters, wash feet in lukewarm water, keep skin moisturized, and have annual diabetic foot exams.',
        'prevention_km': 'ពិនិត្យមើលបាតជើងរាល់ថ្ងៃដើម្បីរកមើលរបួស ឬពងបែក លាងជើងជាមួយទឹកក្តៅឧណ្ហៗ លាបឡេផ្តល់សំណើម និងពិនិត្យជើងជាមួយគ្រូពេទ្យជារៀងរាល់ឆ្នាំ។',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 500,
    },
    {
        'key': 'tingling_hands_feet',
        'label': 'Tingling In Hands/Feet',
        'label_km': 'រមួលដៃឬជើង (ស្រពន់ស្រពាក់)',
        'medical_term': 'Peripheral neuropathy',
        'category': 'neuropathy',
        'question': 'Do you feel tingling, numbness, or pins-and-needles in your hands or feet?',
        'question_km': 'តើអ្នកមានអារម្មណ៍ស្រពន់ ឬដូចមានម្ជុលចាក់នៅចុងដៃចុងជើងដែរឬទេ?',
        'meaning': 'High glucose can irritate small nerve fibres over time.',
        'meaning_km': 'ជាតិស្ករខ្ពស់អាចបំផ្លាញសរសៃប្រសាទតូចៗយូរៗទៅ។',
        'prevention': 'Check your feet daily and keep glucose steady to protect the nerves from further damage.',
        'prevention_km': 'ពិនិត្យជើងរាល់ថ្ងៃ និងរក្សាជាតិស្ករឱ្យមានស្ថិរភាព ដើម្បីការពារសរសៃប្រែះពីការខូចខាតបន្ថែមទៀត។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['tingling'],
        'display_order': 510,
    },
    {
        'key': 'waist_circumference',
        'label': 'Waist Circumference',
        'label_km': 'ទំហំចង្កេះ',
        'medical_term': 'Abdominal obesity / Central adiposity',
        'category': 'risk_factor',
        'question': 'What is your waist measurement at the belly button level (in cm)?',
        'question_km': 'តើទំហំរង្វាស់ចង្កេះរបស់អ្នកនៅត្រង់ផ្ចិតមានប៉ុន្មានសង់ទីម៉ែត្រ (cm)?',
        'meaning': 'Visceral abdominal fat directly secretes inflammatory adipokines that drive hepatic insulin resistance.',
        'meaning_km': 'ខ្លាញ់ក្បាលពោះបញ្ចេញសារធាតុដែលបង្កើនភាពស៊ាំនឹងអាំងស៊ុយលីននៅក្នុងថ្លើម។',
        'prevention': 'Target waist circumference <90 cm for Asian men (<80 cm for Asian women) through aerobic activity and dietary changes.',
        'prevention_km': 'រក្សាទំហំចង្កេះឱ្យនៅក្រោម ៩០ ស.ម សម្រាប់បុរសអាស៊ី (ក្រោម ៨០ ស.ម សម្រាប់ស្ត្រីអាស៊ី) តាមរយៈការហាត់ប្រាណ និងអាហារូបត្ថម្ភ។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 520,
    },
    {
        'key': 'ada_risk_score',
        'label': 'ADA Diabetes Risk Score',
        'label_km': 'ពិន្ទុហានិភ័យទឹកនោមផ្អែម ADA',
        'medical_term': 'American Diabetes Association 7-Point Risk Index',
        'category': 'profile',
        'question': 'Calculated pre-screening diabetes risk index.',
        'question_km': 'សន្ទស្សន៍វាយតម្លៃហានិភ័យជំងឺទឹកនោមផ្អែមបឋម។',
        'meaning': 'A validated clinical scoring tool evaluating age, sex, family history, high blood pressure, physical activity, and BMI.',
        'meaning_km': 'ប្រព័ន្ធវាយតម្លៃគ្លីនិកស្តង់ដារផ្អែកលើអាយុ ភេទ ប្រវត្តិគ្រួសារ សម្ពាធឈាម សកម្មភាពរាងកាយ និងទម្ងន់។',
        'prevention': 'Scores of 5 or higher indicate elevated pre-test probability warranting formal diagnostic bloodwork.',
        'prevention_km': 'ពិន្ទុចាប់ពី ៥ ឡើងទៅបង្ហាញពីហានិភ័យខ្ពស់ដែលតម្រូវឱ្យធ្វើតេស្តឈាមបញ្ជាក់។',
        'weight': 0.20,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 530,
    },
    {
        'key': 'nocturia',
        'label': 'Nocturia (Waking to Urinate)',
        'label_km': 'ភ្ញាក់នោមពេលយប់ (Nocturia)',
        'medical_term': 'Nocturia',
        'category': 'cardinal',
        'question': 'Do you wake up 2 or more times during the night to urinate?',
        'question_km': 'តើអ្នកភ្ញាក់ពីគេងដើម្បីបត់ជើងតូចនៅពេលយប់ចាប់ពី ២ ដងឡើងទៅឬ?',
        'meaning': 'Persistent waking to urinate at night reflects sustained osmotic diuresis from nocturnal hyperglycemia.',
        'meaning_km': 'ការភ្ញាក់នោមពេលយប់ចាប់ពី ២ដងឡើង បង្ហាញពីការបញ្ចេញជាតិស្ករលើសតាមតម្រងនោមពេញមួយយប់។',
        'prevention': 'Monitor blood sugar levels before bedtime and avoid late-night caffeine or high-carbohydrate snacks.',
        'prevention_km': 'តាមដានជាតិស្ករមុនចូលគេង និងជៀសវាងកាហ្វេអ៊ីន ឬអាហារមានជាតិស្ករច្រើននៅពេលយប់។',
        'weight': 0.25,
        'type_indication': 'both',
        'is_cardinal': True,
        'is_emergency': False,
        'display_order': 540,
    },
    {
        'key': 'unquenchable_thirst',
        'label': 'Unquenchable Thirst',
        'label_km': 'ស្រេកទឹកខ្លាំងមិនបាត់',
        'medical_term': 'Severe Polydipsia',
        'category': 'cardinal',
        'question': 'Do you feel a constant, unquenchable thirst despite drinking high amounts of water?',
        'question_km': 'តើអ្នកមានអារម្មណ៍ស្រេកទឹកខ្លាំងមិនចេះបាត់ ទោះបីជាផឹកទឹកច្រើនយ៉ាងណាក៏ដោយឬ?',
        'meaning': 'Extracellular hyperosmolarity signals the hypothalamus to trigger constant thirst to dilute circulating glucose.',
        'meaning_km': 'ជាតិស្ករក្នុងឈាមខ្ពស់ខ្លាំងជំរុញឱ្យខួរក្បាលបញ្ជាឱ្យស្រេកទឹកជាបន្តបន្ទាប់ដើម្បីរំលាយជាតិស្ករ។',
        'prevention': 'Hydrate with plain water rather than juices, sodas, or sweet tea.',
        'prevention_km': 'ផឹកទឹកបរិសុទ្ធ ជៀសវាងភេសជ្ជៈផ្អែម ឬទឹកផ្លែឈើកំប៉ុង។',
        'weight': 0.25,
        'type_indication': 'both',
        'is_cardinal': True,
        'is_emergency': False,
        'display_order': 550,
    },
    {
        'key': 'severe_fatigue',
        'label': 'Severe Persistent Fatigue',
        'label_km': 'អស់កម្លាំងល្ហិតល្ហៃធ្ងន់ធ្ងរ',
        'medical_term': 'Diabetic Asthenia / Chronic Fatigue',
        'category': 'metabolic',
        'question': 'On a scale of 1 to 10, is your daily physical or mental exhaustion at 7 or higher?',
        'question_km': 'លើមាត្រដ្ឋានពី ១ ដល់ ១០ តើកម្រិតអស់កម្លាំងប្រចាំថ្ងៃរបស់អ្នកមានចាប់ពីកម្រិត ៧ ឡើងទៅឬ?',
        'meaning': 'Without sufficient cellular glucose uptake, muscles and brain tissues remain starved for usable ATP energy.',
        'meaning_km': 'នៅពេលកោសិកាមិនអាចទាញយកជាតិស្ករបាន សាច់ដុំ និងខួរក្បាលខ្វះថាមពល បណ្តាលឱ្យអស់កម្លាំងរ៉ាំរ៉ៃ។',
        'prevention': 'Balance complex carbohydrates with protein and ensure regular physical movement to stimulate insulin sensitivity.',
        'prevention_km': 'ទទួលទានអាហារដែលមានតុល្យភាព និងធ្វើចលនារាងកាយទៀងទាត់ដើម្បីបង្កើនភាពប្រែប្រួលនៃអាំងស៊ុយលីន។',
        'weight': 0.18,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 560,
    },
    {
        'key': 'dyslipidemia_low_hdl',
        'label': 'Low HDL Cholesterol',
        'label_km': 'កូឡេស្តេរ៉ុលល្អ (HDL) ទាប',
        'medical_term': 'Hypoalphalipoproteinemia',
        'category': 'risk_factor',
        'question': 'Has a doctor told you that your HDL (good) cholesterol is low (<35 mg/dL)?',
        'question_km': 'តើគ្រូពេទ្យធ្លាប់ប្រាប់ថាជាតិខ្លាញ់ល្អ HDL របស់អ្នកទាប (<៣៥ mg/dL) ដែរឬទេ?',
        'meaning': 'Low HDL cholesterol is a hallmark of the atherogenic diabetic dyslipidemia triad driven by insulin resistance.',
        'meaning_km': 'HDL ទាបជាសញ្ញាសំខាន់នៃភាពស៊ាំនឹងអាំងស៊ុយលីន និងបង្កើនហានិភ័យសរសៃឈាមបេះដូង។',
        'prevention': 'Engage in regular aerobic exercise, consume healthy monounsaturated fats (olive oil, nuts), and eliminate trans fats.',
        'prevention_km': 'ហាត់ប្រាណបែប cardio ទទួលទានខ្លាញ់ល្អ (ប្រេងអូលីវ គ្រាប់ធញ្ញជាតិ) និងជៀសវាងខ្លាញ់មិនល្អ។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 570,
    },
    {
        'key': 'dyslipidemia_high_tg',
        'label': 'High Triglycerides',
        'label_km': 'ទ្រីគ្លីសេរីដខ្ពស់ (Triglycerides)',
        'medical_term': 'Hypertriglyceridemia',
        'category': 'risk_factor',
        'question': 'Are your blood triglyceride levels high (≥250 mg/dL or 2.8 mmol/L)?',
        'question_km': 'តើកម្រិតខ្លាញ់ទ្រីគ្លីសេរីដក្នុងឈាមរបស់អ្នកខ្ពស់ (≥២៥០ mg/dL) ដែរឬទេ?',
        'meaning': 'Hypertriglyceridemia reflects hepatic overproduction of VLDL particles under conditions of hyperinsulinemia.',
        'meaning_km': 'ទ្រីគ្លីសេរីដខ្ពស់ឆ្លុះបញ្ចាំងពីការផលិតជាតិខ្លាញ់លើសលប់ដោយថ្លើមក្រោមឥទ្ធិពលអាំងស៊ុយលីនខ្ពស់។',
        'prevention': 'Cut simple sugars, refined starches, and alcohol, and incorporate omega-3 fatty acids.',
        'prevention_km': 'កាត់បន្ថយជាតិស្ករ ម្សៅកែច្នៃ និងគ្រឿងស្រវឹង ព្រមទាំងបន្ថែមអាស៊ីតខ្លាញ់អូមេហ្គា ៣។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 580,
    },
    {
        'key': 'cardiovascular_disease',
        'label': 'Cardiovascular Disease History',
        'label_km': 'ប្រវត្តិជំងឺសរសៃឈាមបេះដូង',
        'medical_term': 'Atherosclerotic Cardiovascular Disease (ASCVD)',
        'category': 'risk_factor',
        'question': 'Have you had a heart attack, stroke, angina, or peripheral artery disease?',
        'question_km': 'តើអ្នកធ្លាប់មានជំងឺគាំងបេះដូង ដាច់សរសៃឈាមខួរក្បាល ឈឺទ្រូង ឬជំងឺសរសៃឈាមបេះដូងដែរឬទេ?',
        'meaning': 'Diabetes is considered a coronary heart disease equivalent, multiplying cardiovascular event recurrence.',
        'meaning_km': 'ជំងឺទឹកនោមផ្អែមបង្កើនហានិភ័យនៃជំងឺដាច់សរសៃឈាមខួរក្បាល និងជំងឺគាំងបេះដូងទ្វេដង។',
        'prevention': 'Strict blood pressure control (<130/80), lipid optimization with statins if indicated, and daily physical activity.',
        'prevention_km': 'គ្រប់គ្រងសម្ពាធឈាមឱ្យនៅក្រោម ១៣០/៨០ គ្រប់គ្រងជាតិខ្លាញ់ និងហាត់ប្រាណប្រចាំថ្ងៃ។',
        'weight': 0.18,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 590,
    },
    {
        'key': 'macrosomia_history',
        'label': 'Delivered Large Baby (>4.1 kg / 9 lbs)',
        'label_km': 'ធ្លាប់សម្រាលកូនទម្ងន់លើស ៤.១ គីឡូក្រាម',
        'medical_term': 'Fetal Macrosomia Delivery',
        'category': 'risk_factor',
        'question': 'Have you ever given birth to a baby weighing over 9 pounds (4.1 kilograms)?',
        'question_km': 'តើអ្នកធ្លាប់សម្រាលកូនដែលមានទម្ងន់ចាប់ពី ៤ គីឡូក្រាមឡើងទៅដែរឬទេ?',
        'meaning': 'Fetal macrosomia reflects maternal gestational hyperglycemia passing excess glucose across the placenta.',
        'meaning_km': 'ការសម្រាលកូនថ្លោសលើស ៤.១ គ.ក្រ បង្ហាញពីជាតិស្ករខ្ពស់របស់ម្តាយក្នុងពេលមានផ្ទៃពោះ។',
        'prevention': 'Regular postpartum fasting glucose or HbA1c screening every 1–3 years for lifetime Type 2 risk.',
        'prevention_km': 'ពិនិត្យជាតិស្ករឈាម ឬ HbA1c រៀងរាល់ ១ ទៅ ៣ ឆ្នាំម្តង ព្រោះមានហានិភ័យកើតជំងឺទឹកនោមផ្អែមប្រភេទទី ២ ពេញមួយជីវិត។',
        'weight': 0.14,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 600,
    },
    {
        'key': 'physical_inactivity',
        'label': 'Physical Inactivity (<150 min/week)',
        'label_km': 'កង្វះសកម្មភាពរាងកាយ (<១៥០ នាទី/សប្តាហ៍)',
        'medical_term': 'Physical Inactivity',
        'category': 'risk_factor',
        'question': 'Do you complete less than 150 minutes of moderate physical activity per week?',
        'question_km': 'តើអ្នកធ្វើសកម្មភាពរាងកាយ ឬហាត់ប្រាណតិចជាង ១៥០ នាទីក្នុងមួយសប្តាហ៍ឬ?',
        'meaning': 'Skeletal muscle is the primary site of postprandial glucose disposal; inactivity downregulates GLUT4 transporters.',
        'meaning_km': 'សាច់ដុំជាកន្លែងដុតរំលាយជាតិស្ករសំខាន់។ កង្វះការធ្វើចលនាធ្វើឱ្យថយចុះការស្រូបយកជាតិស្ករ។',
        'prevention': 'Aim for at least 150 minutes per week of moderate aerobic exercise (brisk walking, swimming) plus 2 resistance training sessions.',
        'prevention_km': 'ហាត់ប្រាណកម្រិតមធ្យមយ៉ាងតិច ១៥០ នាទីក្នុងមួយសប្តាហ៍ (ដើរលឿន ហែលទឹក) និងលើកទម្ងន់ ២ដងក្នុងមួយសប្តាហ៍។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 610,
    },
    {
        'key': 'sugary_diet',
        'label': 'High Sugary & Ultra-Processed Diet',
        'label_km': 'ការទទួលទានអាហារផ្អែម និងអាហារកែច្នៃខ្ពស់',
        'medical_term': 'High Glycemic Dietary Pattern',
        'category': 'risk_factor',
        'question': 'Do you frequently consume sugary beverages, sweets, or refined carbohydrates several times a week?',
        'question_km': 'តើអ្នកទទួលទានភេសជ្ជៈផ្អែម អាហារផ្អែម ឬម្សៅកែច្នៃញឹកញាប់ច្រើនដងក្នុងមួយសប្តាហ៍ឬ?',
        'meaning': 'Rapid glycemic spikes trigger repeated insulin surges, accelerating pancreatic beta-cell fatigue and visceral fat accumulation.',
        'meaning_km': 'ការឡើងចុះជាតិស្ករលឿនជំរុញឱ្យលំពែងបញ្ចេញអាំងស៊ុយលីនច្រើនជ្រុល ធ្វើឱ្យលំពែងឆាប់ចុះខ្សោយ និងកើនឡើងខ្លាញ់ក្បាលពោះ។',
        'prevention': 'Replace sugar-sweetened beverages with water or unsweetened tea; focus on whole grains, legumes, and green vegetables.',
        'prevention_km': 'ជំនួសភេសជ្ជៈផ្អែមដោយទឹកស្អាត ឬតែគ្មានជាតិស្ករ ហើយផ្តោតលើគ្រាប់ធញ្ញជាតិ និងបន្លែបៃតង។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 620,
    },
    {
        'key': 'sleep_deprivation_apnea',
        'label': 'Short Sleep (<6 hrs) or Sleep Apnea',
        'label_km': 'ការគេងមិនគ្រប់ (<៦ ម៉ោង) ឬបញ្ហាដង្ហើមពេលគេង (Apnea)',
        'medical_term': 'Sleep Disruption / Obstructive Sleep Apnea',
        'category': 'risk_factor',
        'question': 'Do you average less than 6 hours of sleep per night or experience heavy snoring / daytime sleepiness?',
        'question_km': 'តើអ្នកគេងមិនគ្រប់គ្រាន់ (តិចជាង ៦ ម៉ោងក្នុងមួយយប់) ឬមានការស្រមុកខ្លាំង និងងងុយគេងពេលថ្ងៃឬ?',
        'meaning': 'Sleep deprivation stimulates nighttime cortisol, growth hormone, and sympathetic tone, producing morning insulin resistance.',
        'meaning_km': 'ការគេងមិនគ្រប់បង្កើនអ័រម៉ូនស្ត្រេស cortisol ដែលបង្កើនភាពស៊ាំនឹងអាំងស៊ុយលីននៅពេលព្រឹក។',
        'prevention': 'Prioritize 7–8 hours of restorative sleep, practice sleep hygiene, and consult a physician if loud snoring or gasping occurs.',
        'prevention_km': 'គេងឱ្យបាន ៧ ទៅ ៨ ម៉ោងក្នុងមួយយប់ អនុវត្តអនាម័យនៃការគេង និងពិគ្រោះជាមួយគ្រូពេទ្យបើស្រមុកខ្លាំង។',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 630,
    },
    {
        'key': 'alcohol_frequent',
        'label': 'Heavy or Frequent Alcohol Intake',
        'label_km': 'ការទទួលទានគ្រឿងស្រវឹងច្រើនឬញឹកញាប់',
        'medical_term': 'Excessive Alcohol Consumption',
        'category': 'risk_factor',
        'question': 'Do you consume more than 7 (for women) or 14 (for men) alcoholic drinks per week?',
        'question_km': 'តើអ្នកទទួលទានគ្រឿងស្រវឹងច្រើន (លើសពី ៧ កែវ/សប្តាហ៍សម្រាប់ស្ត្រី ឬ ១៤ កែវ/សប្តាហ៍សម្រាប់បុរស) ឬ?',
        'meaning': 'Excessive alcohol impairs hepatic gluconeogenesis, worsens hypertriglyceridemia, and impairs glycemic control.',
        'meaning_km': 'ការទទួលទានគ្រឿងស្រវឹងច្រើនបំផ្លាញមុខងារថ្លើម បង្កើនជាតិខ្លាញ់ទ្រីគ្លីសេរីដ និងរំខានដល់ការគ្រប់គ្រងជាតិស្ករ។',
        'prevention': 'Limit alcohol to no more than 1 standard drink daily for women and 2 for men, and never drink on an empty stomach.',
        'prevention_km': 'កម្រិតការផឹកត្រឹម ១កែវស្តង់ដារក្នុងមួយថ្ងៃសម្រាប់ស្ត្រី និង ២កែវសម្រាប់បុរស ហើយកុំផឹកពេលពោះទទេ។',
        'weight': 0.10,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 640,
    },
    {
        'key': 'urine_ketones',
        'label': 'Urine Ketones Present',
        'label_km': 'វត្តមានសារធាតុ Ketone ក្នុងទឹកនោម',
        'medical_term': 'Ketonuria',
        'category': 'emergency',
        'question': 'Are ketones positive/present on your urine test strip?',
        'question_km': 'តើបន្ទះតេស្តទឹកនោមរបស់អ្នកបង្ហាញលទ្ធផលវិជ្ជមានជាតិគីតូន (Ketones) ដែរឬទេ?',
        'meaning': 'Ketonuria indicates critical lack of effective insulin forcing the body to break down fat into acidic ketone bodies.',
        'meaning_km': 'វត្តមាន ketone ក្នុងទឹកនោមបង្ហាញពីការខ្វះអាំងស៊ុយលីនធ្ងន់ធ្ងរ ដែលរុញរាងកាយឱ្យដុតបំផ្លាញជាតិខ្លាញ់ទៅជាជាតិអាស៊ីត។',
        'prevention': 'Requires immediate emergency clinical triage with intravenous hydration and insulin therapy to prevent fatal DKA.',
        'prevention_km': 'ត្រូវការការសង្គ្រោះបន្ទាន់ភ្លាមៗតាមរយៈការចាក់បញ្ចូលជាតិទឹក និងអាំងស៊ុយលីន ដើម្បីទប់ស្កាត់គ្រោះថ្នាក់ DKA។',
        'weight': 0.35,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 650,
    },
]
