"""Doctor-manageable fact/symptom knowledge catalog - seed data.

Every entry is a fact key the inference engine and interview exchange
(symptoms, risk factors, labs, profile flags). Each row carries:

- patient-facing education: label / medical term / meaning / prevention (EN + KM)
- reasoning inputs: weight, type_indication, is_cardinal, is_emergency, aliases

Seeding inserts MISSING rows only (see app.utils.seed._seed_fact_catalog) so
doctor edits made in the Knowledge Base always win. This system is a
screening/decision-support aid, not a diagnosis.
"""

FACT_CATALOG_SEED = [

    {
        'key': 'excessive_hunger',
        'label': 'Excessive Hunger',
        'label_km': 'ហៀរស្រេកអាហារខ្លាំង',
        'medical_term': 'Polyphagia',
        'category': 'cardinal',
        'question': 'Do you feel hungry all the time, even after eating?',
        'meaning': 'Can occur when glucose cannot effectively enter cells.',
        'meaning_km': 'អាចកើតឡើងពេលជាតិស្ករចូលទៅក្នុងក្រឡាក្រូបសាចមិនបាន។',
        'prevention': 'Eat balanced meals with fibre and protein so energy is released slowly.',
        'prevention_km': 'ទទួលទានអាហារពេញលេញដែលមានជាតិសរសៃ និងប្រូតេអ៊ីន ដើម្បីឱ្យថាមពលបញ្ចេញបន្តិចម្តងៗ។',
        'weight': 0.25,
        'type_indication': 'both',
        'is_cardinal': True,
        'is_emergency': False,
        'aliases': ['polyphagia'],
        'display_order': 10,
    },
    {
        'key': 'excessive_thirst',
        'label': 'Excessive Thirst',
        'label_km': 'ស្រេកទឹកខ្លាំង',
        'medical_term': 'Polydipsia',
        'category': 'cardinal',
        'question': 'Do you feel unusually thirsty, even after drinking water?',
        'meaning': 'Can occur when blood glucose is high — the body pulls water to dilute the sugar.',
        'meaning_km': 'អាចកើតឡើងពេលជាតិស្ករក្នុងឈាមខ្ពស់ — រាងកាយទាញទឹកដើម្បីបន្ថយប្រភេទស្ករ។',
        'prevention': 'Drink water regularly and keep blood sugar in the target range; avoid sugary drinks.',
        'prevention_km': 'ផឹកទឹកឱ្យបានទៀងទាត់ និងរក្សាជាតិស្ករក្នុងឈាមឱ្យនៅកម្រិតគោលដៅ។ ជៀសវាងភេសជ្ជៈមានជាតិស្ករ។',
        'weight': 0.3,
        'type_indication': 'both',
        'is_cardinal': True,
        'is_emergency': False,
        'aliases': ['polydipsia'],
        'display_order': 20,
    },
    {
        'key': 'frequent_urination',
        'label': 'Frequent Urination',
        'label_km': 'នោមញឹកញាប់',
        'medical_term': 'Polyuria',
        'category': 'cardinal',
        'question': 'Do you need to urinate more often than usual, especially at night?',
        'meaning': 'Often accompanies high blood glucose — the kidneys flush out the extra sugar.',
        'meaning_km': 'ភាគច្រើនមកជាមួយជាតិស្ករខ្ពស់ — តណ្ហាប្រឹងប្រែងបញ្ចេញស្ករលើសទៅក្រៅ។',
        'prevention': 'Limit caffeine in the evening and keep glucose well controlled to reduce night-time trips.',
        'prevention_km': 'កាត់បន្ថយជាតិកាហ្វេពេលល្ងាច និងគ្រប់គ្រងជាតិស្ករឱ្យបានល្អ ដើម្បីបន្ថយការភ្ញាក់ពេលយប់។',
        'weight': 0.3,
        'type_indication': 'both',
        'is_cardinal': True,
        'is_emergency': False,
        'aliases': ['polyuria'],
        'display_order': 30,
    },
    {
        'key': 'fatigue',
        'label': 'Extreme Fatigue',
        'label_km': 'អស់កម្លាំងប្រចាំ',
        'medical_term': 'Asthenia',
        'category': 'metabolic',
        'question': 'Do you feel unusually tired or exhausted, even after rest?',
        'meaning': "Cells don't get enough glucose for energy.",
        'meaning_km': 'ក្រឡាក្រូបសាចមិនទទួលបានជាតិស្ករគ្រប់គ្រាន់ដើម្បីបង្កើតថាមពល។',
        'prevention': 'Light regular exercise, good sleep and steady meals help restore energy.',
        'prevention_km': 'លំហាត់ប្រាណស្រាលៗជាប្រចាំ ការគេងគ្រប់គ្រាន់ និងអាហារទៀងទាត់ ជួយបង្កើនថាមពលវិញ។',
        'weight': 0.15,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['extreme_fatigue'],
        'display_order': 40,
    },
    {
        'key': 'increased_appetite',
        'label': 'Increased Appetite Despite Eating',
        'category': 'metabolic',
        'question': 'Do you eat more than usual but still feel hungry?',
        'weight': 0.15,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 50,
    },
    {
        'key': 'weakness',
        'label': 'General Weakness',
        'category': 'metabolic',
        'question': 'Do you feel weak or lack energy to do daily activities?',
        'weight': 0.12,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['general_weakness'],
        'display_order': 60,
    },
    {
        'key': 'weight_loss',
        'label': 'Unexplained Weight Loss',
        'label_km': 'ស្រកទម្ងន់ដោយមិនដឹងមូលហេតុ',
        'medical_term': 'Catabolic weight loss',
        'category': 'metabolic',
        'question': 'Have you lost weight without trying or without changing your diet?',
        'meaning': "The body burns fat and muscle for energy when glucose can't enter cells.",
        'meaning_km': 'រាងកាយដុតខ្លាញ់និងសាច់ដុំជំនួសថាមពល ពេលជាតិស្ករចូលក្រឡាក្រូបមិនបាន។',
        'prevention': 'See a doctor soon — sudden weight loss needs checking; balanced meals help rebuild healthy weight.',
        'prevention_km': 'ទៅជួបវេជ្ជបណ្ឌិតឱ្យឆាប់ — ការស្រកទម្ងន់ភ្លាមៗត្រូវការពិនិត្យ។ អាហារពេញលេញជួយសាងសង់ទម្ងន់ដែលមានសុខភាពល្អវិញ។',
        'weight': 0.25,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['unexplained_weight_loss'],
        'display_order': 70,
    },
    {
        'key': 'blurred_vision',
        'label': 'Blurred Or Blurry Vision',
        'label_km': 'មើលមិនច្បាស់',
        'medical_term': 'Lens swelling',
        'category': 'vision',
        'question': 'Is your vision blurry or have you noticed changes in your eyesight?',
        'meaning': "High glucose draws water into the eye's lens, blurring focus.",
        'meaning_km': 'ជាតិស្ករខ្ពស់ទាញទឹកចូលត្រឡប់ភ្នែក ធ្វើឱ្យមើលមិនច្បាស់។',
        'prevention': 'Bring glucose back to target and get an eye exam — vision usually improves as sugar stabilises.',
        'prevention_km': 'នាំជាតិស្ករត្រឡប់មកកម្រិតគោលដៅវិញ និងពិនិត្យភ្នែក — ការមើលឃើញភាគច្រើនប្រសើរឡើងវិញពេលជាតិស្ករមានស្ថិរភាព។',
        'weight': 0.18,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 80,
    },
    {
        'key': 'difficulty_seeing',
        'label': 'Difficulty Seeing At Night',
        'category': 'vision',
        'question': 'Do you have trouble seeing clearly, especially at night?',
        'weight': 0.1,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 90,
    },
    {
        'key': 'acanthosis_nigricans',
        'label': 'Dark Skin Patches',
        'label_km': 'ស្នាមអុចខ្មៅលើស្បែក (Acanthosis Nigricans)',
        'medical_term': 'Acanthosis nigricans',
        'category': 'skin',
        'question': 'Do you have dark, velvety patches of skin, especially on your neck or armpits?',
        'meaning': 'Dark, velvety skin patches — commonly linked with insulin resistance.',
        'meaning_km': 'ស្បែកខ្មៅជ្រួញៗ — ភាគច្រើនទាក់ទងនឹង insulin resistance។',
        'prevention': 'Weight loss and exercise often fade these patches — ask a doctor about insulin resistance.',
        'prevention_km': 'ការបន្ថយទម្ងន់ និងការហាត់ប្រាណជារឿយៗជួយបន្ថយស្នាមខ្មៅៗទាំងនេះ — សួរវេជ្ជបណ្ឌិតអំពីភាពធន់ទ្រាំ insulin។',
        'weight': 0.2,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['dark_skin_patches'],
        'display_order': 100,
    },
    {
        'key': 'frequent_infections',
        'label': 'Frequent Infections',
        'label_km': 'ឆ្លងរោគញឹកញាប់',
        'medical_term': 'Recurrent infections',
        'category': 'skin',
        'question': 'Do you get frequent infections (skin, gum, bladder, or yeast infections)?',
        'meaning': "High glucose weakens the immune system's defences.",
        'meaning_km': 'ជាតិស្ករខ្ពស់ចុះខ្សោយប្រព័ន្ធភាពការពាររាងកាយ។',
        'prevention': 'Keep glucose in range, keep skin clean and dry, and treat infections early.',
        'prevention_km': 'រក្សាជាតិស្ករឱ្យនៅកម្រិតគោលដៅ រក្សាស្បែកស្អាតនិងស្ងួត និងព្យាបាលការឆ្លងទាន់ពេល។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 110,
    },
    {
        'key': 'itchy_skin',
        'label': 'Itchy Or Dry Skin',
        'category': 'skin',
        'question': 'Is your skin unusually dry, itchy, or irritated?',
        'weight': 0.1,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['dry_skin'],
        'display_order': 120,
    },
    {
        'key': 'slow_healing',
        'label': 'Slow Healing Cuts/Bruises',
        'label_km': 'របួសជាសះស្បើយយឺត',
        'medical_term': 'Impaired wound healing',
        'category': 'skin',
        'question': 'Do cuts, bruises, or sores take longer than usual to heal?',
        'meaning': 'High glucose slows blood flow and weakens immune repair.',
        'meaning_km': 'ជាតិស្ករខ្ពស់បន្ថយដំណើរឈាមវិញភាគ និងចុះខ្សោយភាពការពាររាងកាយ។',
        'prevention': 'Clean and protect wounds early and keep glucose in range to speed up healing.',
        'prevention_km': 'សម្អាត និងការពាររបួសទាន់ពេល និងរក្សាជាតិស្ករឱ្យនៅកម្រិតគោលដៅ ដើម្បីឱ្យរបួសជាសះស្បើយលឿនជាង។',
        'weight': 0.18,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['slow_healing_wounds'],
        'display_order': 130,
    },
    {
        'key': 'erectile_dysfunction',
        'label': 'Erectile Dysfunction',
        'category': 'reproductive',
        'question': 'Have you experienced erectile dysfunction or sexual problems? (For males)',
        'weight': 0.1,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 140,
    },
    {
        'key': 'yeast_infections',
        'label': 'Recurrent Yeast Infections',
        'category': 'reproductive',
        'question': 'Do you have frequent vaginal yeast infections? (For females)',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 150,
    },
    {
        'key': 'difficulty_concentrating',
        'label': 'Difficulty Concentrating',
        'category': 'mental',
        'question': 'Do you have trouble concentrating or thinking clearly?',
        'weight': 0.08,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 160,
    },
    {
        'key': 'irritability',
        'label': 'Irritability Or Mood Changes',
        'label_km': 'អាក់អន់ចិត្ត / ប្រែប្រួលអារម្មណ៍',
        'medical_term': 'Mood changes',
        'category': 'mental',
        'question': 'Have you been more irritable or experienced mood swings?',
        'meaning': 'Blood sugar swings can affect mood and concentration.',
        'meaning_km': 'ជាតិស្ករឡើងចុះអាចប៉ះពាល់អារម្មណ៍និងការផ្ចង់អារម្មណ៍។',
        'prevention': 'Steady meals, sleep and glucose control can lift mood — seek support if it persists.',
        'prevention_km': 'អាហារទៀងទាត់ ការគេងគ្រប់គ្រាន់ និងការគ្រប់គ្រងជាតិស្ករ អាចធ្វើឱ្យអារម្មណ៍ប្រសើរ — សុំការជួយប្រសិនបើវាបន្តយូរ។',
        'weight': 0.08,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 170,
    },
    {
        'key': 'abdominal_pain',
        'label': 'Abdominal Pain',
        'label_km': 'ឈឺពោះ',
        'medical_term': 'Abdominal pain',
        'category': 'emergency',
        'question': 'Do you have stomach pain or cramping?',
        'meaning': 'With very high glucose this can signal DKA — seek care urgently.',
        'meaning_km': 'ពេលជាតិស្ករខ្ពស់ខ្លាំងអាចជាសញ្ញា DKA — ទៅពេទ្យបន្ទាន់។',
        'prevention': 'Get medical help promptly, especially with vomiting or high sugar — possible DKA.',
        'prevention_km': 'ទៅរកជំនួយវេជ្ជសាស្ត្រឱ្យឆាប់ ជាពិសេសពេលក្អួត ឬជាតិស្ករខ្ពស់ — អាចជា DKA។',
        'weight': 0.12,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 180,
    },
    {
        'key': 'confusion',
        'label': 'Confusion Or Difficulty Staying Awake',
        'category': 'emergency',
        'question': 'Do you feel confused or have trouble staying awake?',
        'weight': 0.2,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 190,
    },
    {
        'key': 'crisis',
        'label': 'Crisis (Emergency Signs)',
        'category': 'emergency',
        'weight': 0.2,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': True,
        'aliases': ['unequivocal_hyperglycemia_or_crisis'],
        'display_order': 200,
    },
    {
        'key': 'fruity_breath',
        'label': 'Fruity-Smelling Breath',
        'label_km': 'ដង្ហើមមានក្លិនផ្លែឈើ',
        'medical_term': 'Ketone breath',
        'category': 'emergency',
        'question': 'Have others noticed a fruity or sweet smell to your breath?',
        'meaning': 'Possible diabetic ketoacidosis (DKA) — seek care urgently.',
        'meaning_km': 'អាចជា DKA (ketone ខ្ពស់) — ត្រូវទៅពេទ្យបន្ទាន់។',
        'prevention': 'This can signal DKA (a dangerous chemical imbalance) — check ketones and seek urgent care.',
        'prevention_km': 'នេះអាចជាសញ្ញា DKA (ភាពមិនតុល្យភាពគីមីដ៏អាចម៍ផ្សែ) — ពិនិត្យ ketones និងស្វែងរកការព្យាបាលសង្គ្រោះបន្ទាន់។',
        'weight': 0.18,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 210,
    },
    {
        'key': 'nausea',
        'label': 'Nausea',
        'label_km': 'ចង់ក្អួត (Nausea)',
        'medical_term': 'Nausea',
        'category': 'emergency',
        'question': 'Do you feel nauseous or sick to your stomach?',
        'meaning': 'Can occur when blood glucose or ketones are very high.',
        'meaning_km': 'អាចកើតពេលជាតិស្ករឬ ketone ខ្ពស់ខ្លាំង។',
        'prevention': 'Sip water slowly and seek care if it persists — nausea with high sugar can be serious.',
        'prevention_km': 'ពឹងទឹកបន្តិចម្តងៗ និងទៅពិនិត្យប្រសិនបើវាបន្ត — ក្អួតចង្អោរជាមួយជាតិស្ករខ្ពស់អាចមានគ្រោះថ្នាក់។',
        'weight': 0.1,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 220,
    },
    {
        'key': 'rapid_breathing',
        'label': 'Rapid Or Deep Breathing',
        'category': 'emergency',
        'question': 'Are you breathing faster or deeper than normal?',
        'weight': 0.15,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 230,
    },
    {
        'key': 'unable_to_keep_fluids',
        'label': 'Unable to Keep Fluids Down',
        'category': 'emergency',
        'weight': 0.2,
        'type_indication': 'both',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 240,
    },
    {
        'key': 'vomiting',
        'label': 'Vomiting',
        'label_km': 'ក្អួត',
        'medical_term': 'Vomiting',
        'category': 'emergency',
        'question': 'Have you been vomiting?',
        'meaning': 'With very high glucose this can signal DKA — seek care urgently.',
        'meaning_km': 'ពេលជាតិស្ករខ្ពស់ខ្លាំងអាចជាសញ្ញា DKA — ទៅពេទ្យបន្ទាន់។',
        'prevention': 'Seek medical care quickly — vomiting with high glucose risks dehydration and DKA.',
        'prevention_km': 'ទៅរកការព្យាបាលវេជ្ជសាស្ត្រឱ្យលឿន — ការក្អួតជាមួយជាតិស្ករខ្ពស់មានហានិភ័យភាពស្រកទឹក និង DKA។',
        'weight': 0.15,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 250,
    },
    {
        'key': 'bed_wetting',
        'label': 'Bed-Wetting',
        'label_km': 'ក្រពៅលើគ្រែថ្មី (កុមារ)',
        'medical_term': 'Nocturnal enuresis',
        'category': 'pediatric',
        'question': 'Has bed-wetting started after being dry at night? (For children)',
        'meaning': 'Extra glucose pulls more water — a classic Type 1 sign in children.',
        'meaning_km': 'ជាតិស្ករលើសទាញទឹកច្រើន — សញ្ញាសំខាន់នៃប្រភេទទី 1 ក្នុងកុមារ។',
        'prevention': 'A quick glucose check today can rule out early diabetes — see a doctor promptly.',
        'prevention_km': 'ធ្វើតេស្តជាតិស្ករឆាប់រហ័សថ្ងៃនេះ អាចច្បាស់កាត់ជំងឺទឹកនោមផ្អែមដំណាក់កាលដំបូង — ទៅជួបវេជ្ជបណ្ឌិតឱ្យឆាប់។',
        'weight': 0.18,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 260,
    },
    {
        'key': 'diaper_rash',
        'label': 'Persistent Diaper Rash',
        'category': 'pediatric',
        'question': "Does the child have a persistent diaper rash that won't heal? (For infants)",
        'weight': 0.1,
        'type_indication': 'type1',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 270,
    },
    {
        'key': 'deep_rapid_breathing',
        'label': 'Deep Rapid Breathing',
        'label_km': 'ដកដង្ហើមជ្រៅ លឿន',
        'medical_term': 'Kussmaul breathing',
        'category': 'other',
        'meaning': 'The body tries to release ketone acids — seek care urgently.',
        'meaning_km': 'រាងកាយប្រឹងប្រែងបញ្ចេញអាស៊ីត ketone — ត្រូវទៅពេទ្យបន្ទាន់។',
        'prevention': 'An emergency sign (possible DKA) — go to emergency care immediately.',
        'prevention_km': 'សញ្ញាសង្គ្រោះបន្ទាន់ (អាចជា DKA) — ទៅព្យាបាលសង្គ្រោះបន្ទាន់ភ្លាមៗ។',
        'weight': 0.05,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': True,
        'display_order': 280,
    },
    {
        'key': 'dizziness',
        'label': 'Dizziness',
        'label_km': 'វិលមុខ',
        'medical_term': 'Dizziness',
        'category': 'other',
        'meaning': 'Can come from low — or very high — blood sugar.',
        'meaning_km': 'អាចមកពីជាតិស្ករទាប — ឬខ្ពស់ខ្លាំង។',
        'prevention': 'Sit down and check glucose; treat lows quickly and seek help if it is severe.',
        'prevention_km': 'អង្គុយចុះ និងពិនិត្យជាតិស្ករ។ ព្យាបាលជាតិស្ករទាបឱ្យលឿន និងទៅរកជំនួយប្រសិនបើធ្ងន់ធ្ងរ។',
        'weight': 0.05,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 290,
    },
    {
        'key': 'recurrent_uti_yeast',
        'label': 'Recurrent Uti Yeast',
        'label_km': 'ឆ្លងទឹកនោម / ផ្សិតញឹកញាប់',
        'medical_term': 'Recurrent UTI / yeast infections',
        'category': 'other',
        'meaning': 'Glucose in urine feeds bacteria and yeast.',
        'meaning_km': 'ជាតិស្ករក្នុងនោមធ្វើឱ្យបាកតេរី និងផ្សិតលូតលាស់។',
        'prevention': 'Control sugar levels, stay hydrated, and see a doctor for infections that keep coming back.',
        'prevention_km': 'គ្រប់គ្រងកម្រិតជាតិស្ករ ផឹកទឹកឱ្យបានគ្រប់គ្រាន់ និងទៅជួបវេជ្ជបណ្ឌិតពេលមានការឆ្លងមេរោគដដែលៗ។',
        'weight': 0.05,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 300,
    },
    {
        'key': 'shaking',
        'label': 'Shaking',
        'label_km': 'ញ័រដៃជើង',
        'medical_term': 'Tremor',
        'category': 'other',
        'meaning': 'Common warning sign of low blood sugar (hypoglycemia).',
        'meaning_km': 'សញ្ញាទូទៅនៃជាតិស្ករទាប (hypoglycemia)។',
        'prevention': 'Test glucose now — trembling often means low sugar; use the 15/15 rule if below 70 mg/dL.',
        'prevention_km': 'ពិនិត្យជាតិស្ករភ្លាម — ការញ័រភាគច្រើនមានន័យថាជាតិស្ករទាប។ ប្រើក្បួន ១៥/១៥ ប្រសិនបើក្រោម ៧០ mg/dL។',
        'weight': 0.05,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 310,
    },
    {
        'key': 'sweating',
        'label': 'Sweating',
        'label_km': 'បែកញើសខ្លាំង',
        'medical_term': 'Diaphoresis',
        'category': 'other',
        'meaning': 'Can be a warning sign of low blood sugar (hypoglycemia).',
        'meaning_km': 'អាចជាសញ្ញាជាតិស្ករទាប (hypoglycemia)។',
        'prevention': 'Check blood sugar — sweating can signal a low; keep fast-acting sugar within reach.',
        'prevention_km': 'ពិនិត្យជាតិស្ករក្នុងឈាម — ញៀរញាប់អាចជាសញ្ញាជាតិស្ករទាប។ កាន់ស្កររលត់លឿននៅជាប់ខ្លួនជានិច្ច។',
        'weight': 0.05,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 320,
    },
    {
        'key': 'ethnicity_high_risk',
        'label': 'High-Risk Ethnicity',
        'label_km': 'ជាតិសាសន៍ដែលមានហានិភ័យខ្ពស់',
        'category': 'risk_factor',
        'meaning': 'Some ethnic groups (South Asian, Southeast Asian and others) face higher risk at lower weights — screen earlier.',
        'meaning_km': 'ជនជាតិខ្លះ (អាស៊ីខាងត្បូង អាស៊ីអាគ្នេយ៍ ជាដើម) មានហានិភ័យខ្ពស់ជាង ទោះទម្ងន់ធម្មតា — គួរពិនិត្យទាន់ពេលជាង។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 330,
    },
    {
        'key': 'family_history',
        'label': 'Family History of Diabetes',
        'label_km': 'ប្រវត្តិគ្រួសារ',
        'category': 'risk_factor',
        'meaning': 'A parent or sibling with diabetes raises your lifetime risk — screening should start earlier and repeat regularly.',
        'meaning_km': 'បើមានឪពុកម្តាយ ឬបងប្អូនជំងឺទឹកនោមផ្អែម ហានិភ័យរបស់អ្នកកើនឡើង — គួរពិនិត្យទាន់ពេល និងធ្វើជាប្រចាំ។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['family_history_diabetes'],
        'display_order': 340,
    },
    {
        'key': 'gestational_history',
        'label': 'Prior Gestational Diabetes',
        'label_km': 'ប្រវត្តិទឹកនោមផ្អែមពេលមានផ្ទៃពោះ (Gestational Diabetes)',
        'category': 'risk_factor',
        'meaning': 'Diabetes during pregnancy means a high chance of type 2 later in life — test every 1–3 years.',
        'meaning_km': 'ទឹកនោមផ្អែមពេលមានផ្ទៃពោះ មានឱកាសខ្ពស់ក្លាយជាប្រភេទទី ២ ពេលអនាគត — គួរពិនិត្យរាល់ ១–៣ ឆ្នាំ។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 350,
    },
    {
        'key': 'high_cholesterol',
        'label': 'High Cholesterol',
        'label_km': 'Cholesterol ខ្ពស់',
        'category': 'risk_factor',
        'meaning': 'High cholesterol together with high sugar speeds up artery damage — diet, movement and medication help.',
        'meaning_km': 'ជាតិប្រេងខ្ពស់ទៅជាមួយជាតិស្ករខ្ពស់ ធ្វើឱ្យសរសៃឈាមខូចលឿនជាង — អាហារូបត្ថម្ភ ការហាត់ប្រាណ និងថ្នាំជួយបាន។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 360,
    },
    {
        'key': 'hypertension',
        'label': 'High Blood Pressure',
        'label_km': 'សម្ពាធឈាមខ្ពស់ (Hypertension)',
        'category': 'risk_factor',
        'meaning': 'High blood pressure often travels with high sugar and doubles the risk to the heart and kidneys.',
        'meaning_km': 'សម្ពាធឈាមខ្ពស់ជារឿយៗមកជាមួយជាតិស្ករខ្ពស់ និងបង្កើនហានិភ័យដល់បេះដូង និងតម្រងនោមទ្វេដង។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 370,
    },
    {
        'key': 'obesity',
        'label': 'Obesity',
        'label_km': 'ភាពធាត់ / លើសទម្ងន់ (Obesity)',
        'category': 'risk_factor',
        'meaning': 'Excess body fat — especially around the waist — makes the body resistant to insulin, the top driver of type 2 diabetes.',
        'meaning_km': 'ខ្លាញ់លើសពិសេសនៅជុំវិញពោះ ធ្វើឱ្យរាងកាយធន់ទ្រាំនឹង insulin ដែលជាមូលហេតុចម្បងនៃជំងឺទឹកនោមផ្អែមប្រភេទទី ២។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 380,
    },
    {
        'key': 'overweight',
        'label': 'Overweight (BMI 25-30)',
        'category': 'risk_factor',
        'meaning': 'A BMI of 25–30 already raises type 2 risk; a modest 5–10% weight loss brings it down sharply.',
        'meaning_km': 'BMI ចន្លោះ ២៥–៣០ បង្កើនហានិភ័យប្រភេទទី ២ រួចទៅហើយ។ បន្ថយទម្ងន់ ៥–១០% អាចកាត់បន្ថយវាយ៉ាងខ្លាំង។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 390,
    },
    {
        'key': 'pcos_history',
        'label': 'PCOS History',
        'label_km': 'ប្រវត្តិជំងឺ PCOS',
        'category': 'risk_factor',
        'meaning': 'PCOS is strongly linked to insulin resistance — women with PCOS need regular glucose checks.',
        'meaning_km': 'PCOS ទាក់ទងយ៉ាងខ្លាំងនឹងភាពធន់ទ្រាំ insulin — ស្ត្រីដែលមាន PCOS គួរពិនិត្យជាតិស្ករជាប្រចាំ។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 400,
    },
    {
        'key': 'sedentary_lifestyle',
        'label': 'Sedentary Lifestyle',
        'label_km': 'មិនសូវមានសកម្មភាពរាងកាយ',
        'category': 'risk_factor',
        'meaning': 'Sitting most of the day weakens glucose control — 150 minutes of movement a week cuts risk by about a third.',
        'meaning_km': 'អង្គុយភាគច្រើនក្នុងមួយថ្ងៃ ធ្វើឱ្យការគ្រប់គ្រងជាតិស្ករអន់ជាង។ ហាត់ប្រាណ ១៥០ នាទីក្នុងមួយសប្តាហ៍ អាចកាត់បន្ថយហានិភ័យប្រហែលមួយភាគបី។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['physical_activity_low'],
        'display_order': 410,
    },
    {
        'key': 'smoking',
        'label': 'Smoking',
        'label_km': 'អ្នកកំពុងជក់បារី',
        'category': 'risk_factor',
        'meaning': 'Smoking worsens insulin resistance and damages blood vessels — quitting is the single best step.',
        'meaning_km': 'ជក់បារីធ្វើឱ្យភាពធន់ទ្រាំ insulin ធ្ងន់ធ្ងរ និងខូចសរសៃឈាម — ការលះបង់ជក់បារីជាជំហានល្អបំផុត។',
        'weight': 0.05,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 420,
    },
    {
        'key': '2h_ogtt_75g',
        'label': '2-Hour OGTT (75 g)',
        'category': 'lab',
        'meaning': 'Blood glucose 2 hours after a 75 g glucose drink. Normal <140 mg/dL, prediabetes 140-199 mg/dL, diabetes >=200 mg/dL (ADA).',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['two_hour_ogtt_75g', 'ogtt_2h'],
        'display_order': 430,
    },
    {
        'key': 'fasting_glucose',
        'label': 'Fasting Plasma Glucose',
        'category': 'lab',
        'meaning': 'Glucose after at least 8 hours without food. Normal <100 mg/dL, prediabetes 100-125 mg/dL, diabetes >=126 mg/dL (ADA).',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['fasting_plasma_glucose'],
        'display_order': 440,
    },
    {
        'key': 'hba1c',
        'label': 'HbA1c',
        'category': 'lab',
        'meaning': 'Average blood glucose over about 3 months. Normal <5.7%, prediabetes 5.7-6.4%, diabetes >=6.5% (ADA).',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['a1c'],
        'display_order': 450,
    },
    {
        'key': 'random_plasma_glucose',
        'label': 'Random Plasma Glucose',
        'category': 'lab',
        'meaning': 'Glucose at any time of day. >=200 mg/dL together with classic symptoms suggests diabetes (ADA).',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['random_glucose'],
        'display_order': 460,
    },
    {
        'key': 'currently_pregnant',
        'label': 'Currently Pregnant',
        'category': 'profile',
        'meaning': 'Pregnancy uses stricter glucose thresholds (IADPSG): fasting >=92, 1 h >=180, or 2 h >=153 mg/dL on a 75 g OGTT indicates gestational diabetes.',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 470,
    },
    {
        'key': 'rapid_onset',
        'label': 'Rapid Symptom Onset',
        'category': 'profile',
        'meaning': 'Symptoms appearing suddenly over days to weeks fit the Type 1 pattern; gradual onset over years fits Type 2.',
        'weight': 0.0,
        'type_indication': 'none',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 480,
    },
    {
        'key': 'burning_sensation',
        'label': 'Burning Sensation In Extremities',
        'category': 'neuropathy',
        'question': 'Do you feel burning sensations in your hands, feet, or legs?',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 490,
    },
    {
        'key': 'numbness',
        'label': 'Numbness In Extremities',
        'category': 'neuropathy',
        'question': 'Have you noticed numbness or loss of feeling in your hands or feet?',
        'weight': 0.12,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'display_order': 500,
    },
    {
        'key': 'tingling_hands_feet',
        'label': 'Tingling In Hands/Feet',
        'label_km': 'រមួលដៃឬជើង',
        'medical_term': 'Peripheral neuropathy',
        'category': 'neuropathy',
        'question': 'Do you feel tingling, numbness, or pins-and-needles in your hands or feet?',
        'meaning': 'High glucose can irritate small nerve fibres over time.',
        'meaning_km': 'ជាតិស្ករខ្ពស់អាចបំផ្លាញសរសៃប្រសាទតូចៗយូរៗទៅ។',
        'prevention': 'Check your feet daily and keep glucose steady to protect the nerves from further damage.',
        'prevention_km': 'ពិនិត្យជើងរាល់ថ្ងៃ និងរក្សាជាតិស្ករឱ្យមានស្ថិរភាព ដើម្បីការពារសរសៃប្រែះពីការខូចខាតបន្ថែមទៀត។',
        'weight': 0.15,
        'type_indication': 'type2',
        'is_cardinal': False,
        'is_emergency': False,
        'aliases': ['tingling'],
        'display_order': 510,
    },
]
