import React from 'react'
import {
  Brain,
  HelpCircle,
  AlertCircle,
  CheckCircle2,
  ShieldCheck,
  Sparkles,
  Info,
  ShieldAlert,
  Flame,
  ArrowRight,
} from 'lucide-react'
import { useLanguage } from '@/contexts/LanguageContext'

/**
 * AiReasoningReportSection
 * =========================
 * Translates the expert system result and evidence into an explainable,
 * patient-friendly AI reasoning report.
 *
 * Core pillars:
 * 1. What the result means
 * 2. Why the result was generated
 * 3. Which findings were most relevant
 * 4. What the result does NOT mean
 *
 * SAFETY GUARDRAIL:
 * Does NOT invent symptoms, labs, or diagnoses.
 * Explicitly marks screening vs confirmed diagnosis.
 */
export function AiReasoningReportSection({
  reasoningReport,
  diagnosis = '',
  certaintyPercent = 0,
  urgency = 'routine',
  hasLabs = false,
  matchedSymptoms = [],
  matchedRiskFactors = [],
  className = '',
}) {
  const { isKhmer } = useLanguage()

  const aiData = reasoningReport?.ai_explanation || {}

  // Fallbacks if backend ai_explanation is partially missing
  const whatItMeans = aiData.what_it_means || (
    isKhmer
      ? `ការវាយតម្លៃរបស់អ្នកបង្ហាញពីទម្រង់ ${diagnosis} ជាមួយនឹងទំនុកចិត្ត ${certaintyPercent}%។ នេះជាការវាយតម្លៃបឋម (Screening) ដើម្បីផ្តល់ការណែនាំសុខភាព មិនមែនជាការសន្និដ្ឋានចុងក្រោយដោយគ្មានការពិនិត្យឈាមផ្ទាល់នោះទេ។`
      : `Your assessment pattern aligns with "${diagnosis}" at ${certaintyPercent}% confidence. This serves as a clinical screening indicator to guide next steps, rather than a definitive diagnosis.`
  )

  const whyGenerated = aiData.why_generated || (
    isKhmer
      ? `លទ្ធផលនេះត្រូវបានបង្កើតឡើងដោយសារប្រព័ន្ធអ្នកជំនាញបានវិភាគលើ ${matchedSymptoms.length} រោគសញ្ញា ${matchedRiskFactors.length > 0 ? `និង ${matchedRiskFactors.length} កត្តាហានិភ័យ` : ''} របស់អ្នក ហើយបានផ្គូផ្គងនឹងក្បួនវិនិច្ឆ័យវេជ្ជសាស្ត្រផ្លូវការ។`
      : `This result was generated because the clinical decision support engine identified ${matchedSymptoms.length} cardinal symptom signal(s)${matchedRiskFactors.length > 0 ? ` and ${matchedRiskFactors.length} predisposing risk factor(s)` : ''}, which triggered standardized diagnostic decision rules.`
  )

  const mostRelevantFindings = aiData.most_relevant_findings || (
    isKhmer
      ? `សញ្ញាដែលមានឥទ្ធិពលបំផុតរួមមាន៖ ${matchedSymptoms.slice(0, 3).join(', ') || 'កត្តាហានិភ័យសុខភាព'}`
      : `The primary drivers for this evaluation were: ${matchedSymptoms.slice(0, 3).join(', ') || 'Identified lifestyle and metabolic indicators'}.`
  )

  const whatItDoesNotMean = aiData.what_it_does_not_mean || [
    isKhmer
      ? 'នេះមិនមែនជាការវិនិច្ឆ័យជំងឺផ្លូវការចុងក្រោយឡើយ — ត្រូវការតេស្តឈាមជាក់ស្តែងពីមន្ទីរពិសោធន៍'
      : 'This is NOT a confirmed diagnosis — only a physician with verified lab tests can provide a definitive diagnosis.',
    isKhmer
      ? 'លទ្ធផលនេះមិនមែនមានន័យថាអ្នកមិនអាចកែលម្អសុខភាពបាននោះទេ — របៀបរស់នៅល្អអាចជួយការពារបានយ៉ាងមានប្រសិទ្ធភាព'
      : 'This does NOT mean the condition is irreversible — lifestyle interventions and timely medical care significantly alter outcomes.',
    ...(certaintyPercent < 60
      ? [
          isKhmer
            ? 'កម្រិតទំនុកចិត្តនៅមានកម្រិត — ត្រូវការទិន្នន័យបន្ថែមដើម្បីការសន្និដ្ឋានច្បាស់លាស់'
            : 'Confidence is moderate — additional laboratory confirmation (fasting glucose or HbA1c) is needed for precision.',
        ]
      : []),
  ]

  const disclaimer = aiData.disclaimer || (
    isKhmer
      ? 'ការវាយតម្លៃនេះត្រូវបានបង្កើតឡើងដោយប្រព័ន្ធគាំទ្រការសម្រេចចិត្តព្យាបាល (Clinical Decision Support) សម្រាប់គោលបំណងពិនិត្យបឋម និងការណែនាំប៉ុណ្ណោះ។ វាមិនជំនួសការពិគ្រោះយោបល់ ការធ្វើរោគវិនិច្ឆ័យ ឬការព្យាបាលពីគ្រូពេទ្យជំនាញឡើយ។'
      : 'This assessment is generated by an expert clinical decision support system for screening and educational guidance only. It does not replace professional medical diagnosis, laboratory testing, or physician consultation.'
  )

  return (
    <div className={`space-y-4 ${className}`}>
      {/* 4 Core Pillars - List Down Style (No Card) */}
      <div className="divide-y divide-slate-100 dark:divide-slate-800">
        {/* 1. What the result means */}
        <div className="py-4 first:pt-0">
          <div className="flex items-center gap-2.5">
            <span className="flex h-6 w-6 items-center justify-center rounded-md bg-indigo-100 dark:bg-indigo-950/70 text-xs font-bold text-indigo-700 dark:text-indigo-300">
              1
            </span>
            <h4 className="text-base font-bold text-slate-900 dark:text-slate-100">
              {isKhmer ? 'អត្ថន័យនៃលទ្ធផលនេះ' : 'What This Result Means'}
            </h4>
          </div>
          <p className="mt-1.5 pl-8 text-xs sm:text-sm leading-relaxed text-slate-700 dark:text-slate-300">
            {whatItMeans}
          </p>
        </div>

        {/* 2. Why the result was generated */}
        <div className="py-4">
          <div className="flex items-center gap-2.5">
            <span className="flex h-6 w-6 items-center justify-center rounded-md bg-sky-100 dark:bg-sky-950/70 text-xs font-bold text-sky-700 dark:text-sky-300">
              2
            </span>
            <h4 className="text-base font-bold text-slate-900 dark:text-slate-100">
              {isKhmer ? 'ហេតុអ្វីបានជាបង្កើតលទ្ធផលនេះ' : 'Why This Result Was Generated'}
            </h4>
          </div>
          <p className="mt-1.5 pl-8 text-xs sm:text-sm leading-relaxed text-slate-700 dark:text-slate-300">
            {whyGenerated}
          </p>
        </div>

        {/* 3. Most relevant findings */}
        <div className="py-4">
          <div className="flex items-center gap-2.5">
            <span className="flex h-6 w-6 items-center justify-center rounded-md bg-teal-100 dark:bg-teal-950/70 text-xs font-bold text-teal-700 dark:text-teal-300">
              3
            </span>
            <h4 className="text-base font-bold text-slate-900 dark:text-slate-100">
              {isKhmer ? 'ភស្តុតាងដែលមានឥទ្ធិពលបំផុត' : 'Most Relevant Findings'}
            </h4>
          </div>
          <p className="mt-1.5 pl-8 text-xs sm:text-sm leading-relaxed text-slate-700 dark:text-slate-300">
            {typeof mostRelevantFindings === 'string'
              ? mostRelevantFindings
              : Array.isArray(mostRelevantFindings)
                ? mostRelevantFindings.join('; ')
                : String(mostRelevantFindings)}
          </p>
        </div>

        {/* 4. What the result does NOT mean */}
        <div className="py-4 last:pb-0">
          <div className="flex items-center gap-2.5">
            <span className="flex h-6 w-6 items-center justify-center rounded-md bg-rose-100 dark:bg-rose-950/70 text-xs font-bold text-rose-700 dark:text-rose-300">
              4
            </span>
            <h4 className="text-base font-bold text-slate-900 dark:text-slate-100">
              {isKhmer ? 'អ្វីដែលលទ្ធផលនេះមិនសំដៅដល់' : 'What This Result Does NOT Mean'}
            </h4>
          </div>
          <ul className="mt-1.5 pl-8 space-y-1 text-xs sm:text-sm text-slate-700 dark:text-slate-300">
            {Array.isArray(whatItDoesNotMean) ? (
              whatItDoesNotMean.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2 leading-relaxed">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-rose-400" />
                  <span>{item}</span>
                </li>
              ))
            ) : (
              <li className="leading-relaxed">
                {whatItDoesNotMean}
              </li>
            )}
          </ul>
        </div>
      </div>

      {/* Safety Notice */}
      <div className="flex items-start gap-2 pt-3 border-t border-slate-100 dark:border-slate-800 text-xs text-slate-500 dark:text-slate-400">
        <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-slate-400" />
        <p className="leading-relaxed">
          <strong className="font-semibold text-slate-700 dark:text-slate-300">
            {isKhmer ? 'ការណែនាំសុវត្ថិភាពវេជ្ជសាស្ត្រ៖ ' : 'Clinical Safety Notice: '}
          </strong>
          {disclaimer}
        </p>
      </div>
    </div>
  )
}

export default AiReasoningReportSection
