"""increase action_value length to text

Revision ID: 656d0bb80d29
Revises: f3c9a4d7b2e1
Create Date: 2026-04-13 17:09:16.618968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656d0bb80d29'
down_revision = 'f3c9a4d7b2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_actions', schema=None) as batch_op:
        batch_op.alter_column('action_value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_actions', schema=None) as batch_op:
        batch_op.alter_column('action_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
